#!/usr/bin/env bash
# =============================================================================
# enable-matomo.sh
#
# Turn on self-hosted Matomo on a *running* DIGIT / CCRS deployment, without a
# full `./deploy.sh <tenant>` (issue #1254). Same shape as its siblings
# enable-dashboard.sh and enable-notifications.sh: it runs ON the box, assumes
# the stack is already up, builds no images, and deploys no platform services.
#
# What it does, in 6 ordered steps:
#   1. Preflight — stack up, overlay present, ports free, disk headroom
#   2. Credentials — MATOMO_* lines in .env, generated once if absent
#   3. Start — `docker compose --profile matomo up -d` for the three services
#   4. Install gate — Matomo's browser installer is the ONE manual step; print
#      the exact tunnel command and stop here until it has been done
#   5. Settings — trusted_hosts + proxy_client_headers (post-install only)
#   6. Verify — endpoints answer, archiver alive, and say what is still missing
#
# WHAT THIS SCRIPT DELIBERATELY DOES NOT DO: edit the nginx vhost.
# /etc/nginx/sites-enabled/<site> is generated by ansible from
# templates/nginx-site.conf.j2, so anything written there by hand is erased by
# the next deploy — silently, and the symptom is analytics that worked for a
# week and then stopped. The durable path is the flag:
#
#     nginx_features:
#       matomo: true          # in inventory/host_vars/<tenant>.yml
#     enable_matomo: true
#     ./deploy.sh <tenant>
#
# preflight.py refuses either of those two flags on its own. Step 6 below tells
# you whether the blocks are live yet.
#
# Usage:
#   ./enable-matomo.sh                 # run all steps in order
#   ./enable-matomo.sh --list          # print the ordered steps + exit
#   ./enable-matomo.sh --help          # full help
#   ./enable-matomo.sh --only step6    # just re-run the verification
#   ./enable-matomo.sh --from step5    # resume after finishing the installer
#   ./enable-matomo.sh --dry-run       # print what it WOULD do, run nothing
#
# Turning it back OFF: set enable_matomo: false and re-deploy. The playbook
# tears the containers down; the two named volumes (and therefore the install
# and every recorded visit) survive.
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# CONFIG — every tunable is an env var with a sane default.
# -----------------------------------------------------------------------------
DIGIT_HOME="${DIGIT_HOME:-/opt/digit}"        # where the compose stack + .env live
MATOMO_PORT="${MATOMO_PORT:-18081}"           # loopback bind; must match upstream_matomo_port
MATOMO_ARCHIVE_INTERVAL="${MATOMO_ARCHIVE_INTERVAL:-3600}"   # seconds between archiving passes
MIN_FREE_GB="${MIN_FREE_GB:-5}"               # refuse to start below this much free disk

STEPS=(step1 step2 step3 step4 step5 step6)
declare -A STEP_DESC=(
  [step1]="Preflight — stack up, overlay present, port free, disk headroom"
  [step2]="Credentials — MATOMO_* in .env (generated once, never rotated here)"
  [step3]="Start — docker compose --profile matomo up -d"
  [step4]="Install gate — the one manual step (Matomo's browser installer)"
  [step5]="Settings — trusted_hosts + proxy_client_headers"
  [step6]="Verify — endpoints, archiver, nginx blocks"
)

DRY_RUN=false
FROM=""; TO=""; ONLY=""

# ── narration ────────────────────────────────────────────────────────────────
if [ -t 1 ]; then C_OK=$'\033[32m'; C_WARN=$'\033[33m'; C_ERR=$'\033[31m'; C_HDR=$'\033[1;36m'; C_OFF=$'\033[0m'
else C_OK=""; C_WARN=""; C_ERR=""; C_HDR=""; C_OFF=""; fi
hdr()  { printf '%s==> [%s/6] %s%s\n' "$C_HDR" "$1" "$2" "$C_OFF"; }
ok()   { printf '     %sOK%s   %s\n'   "$C_OK"   "$C_OFF" "$1"; }
warn() { printf '     %sWARN%s %s\n'   "$C_WARN" "$C_OFF" "$1"; }
fail() { printf '     %sFAIL%s %s\n'   "$C_ERR"  "$C_OFF" "$1" >&2; }
sub()  { printf '          %s\n' "$1"; }
die()  { fail "$1"; exit 1; }
run()  { if $DRY_RUN; then sub "would run: $*"; else "$@"; fi; }

usage() {
  sed -n '2,45p' "$0" | sed 's/^# \{0,1\}//'
  echo
  echo "Steps:"
  for s in "${STEPS[@]}"; do printf '  %-7s %s\n' "$s" "${STEP_DESC[$s]}"; done
}

# The compose -f chain, in the SAME order the ansible playbook composes it
# ("Compute compose -f flags"). Order matters: the per-tenant overlay must come
# last so a tenant can still override anything above it.
compose_files() {
  local f="-f docker-compose.egov-digit.yaml"
  [ -f "$DIGIT_HOME/docker-compose.fast-path.yml" ]  && f="$f -f docker-compose.fast-path.yml"
  [ -f "$DIGIT_HOME/docker-compose.migrations.yml" ] && f="$f -f docker-compose.migrations.yml"
  [ -f "$DIGIT_HOME/docker-compose.monitoring.yml" ] && f="$f -f docker-compose.monitoring.yml"
  f="$f -f docker-compose.matomo.yml"
  # Per-tenant overlays are named docker-compose.<tenant>.yml. Anything that is
  # not one of the well-known names above is one.
  local o
  for o in "$DIGIT_HOME"/docker-compose.*.yml; do
    case "$(basename "$o")" in
      docker-compose.fast-path.yml|docker-compose.migrations.yml|\
      docker-compose.monitoring.yml|docker-compose.matomo.yml) continue ;;
      *) f="$f -f $(basename "$o")" ;;
    esac
  done
  printf '%s' "$f"
}

# ─────────────────────────────────────────────────────────────────────────────
step1() {
  hdr 1 "${STEP_DESC[step1]}"
  [ -d "$DIGIT_HOME" ] || die "$DIGIT_HOME does not exist — is this the DIGIT box?"
  ok "$DIGIT_HOME present"

  docker info >/dev/null 2>&1 || die "cannot talk to the docker daemon (are you in the docker group?)"
  ok "docker reachable"

  if [ ! -f "$DIGIT_HOME/docker-compose.matomo.yml" ]; then
    fail "docker-compose.matomo.yml is not on this box."
    sub "The deploy copies it. Either run ./deploy.sh <tenant> once, or copy it:"
    sub "  scp local-setup/docker-compose.matomo.yml <host>:$DIGIT_HOME/"
    exit 1
  fi
  ok "matomo overlay present"

  # A running platform is not strictly required — Matomo shares nothing with it
  # — but if the stack is down, this is almost certainly not the moment.
  local up; up=$(docker ps --format '{{.Names}}' | grep -c '^digit-\|^egov-' || true)
  if [ "$up" -lt 3 ]; then warn "only $up platform containers running — stack looks down"
  else ok "$up platform containers running"; fi

  # Port must be free OR already held by our own container (idempotent re-run).
  if ss -ltn 2>/dev/null | grep -q ":$MATOMO_PORT "; then
    if docker ps --format '{{.Names}}' | grep -qx digit-matomo; then
      ok "port $MATOMO_PORT held by digit-matomo (already running)"
    else
      die "port $MATOMO_PORT is in use by something else — set MATOMO_PORT and upstream_matomo_port to match"
    fi
  else
    ok "port $MATOMO_PORT free"
  fi

  # Matomo's raw log tables are the thing that grows. Refuse to start a
  # database on a disk that is already tight.
  local free; free=$(df -BG --output=avail "$DIGIT_HOME" | tail -1 | tr -dc '0-9')
  if [ "${free:-0}" -lt "$MIN_FREE_GB" ]; then
    die "only ${free}G free on $DIGIT_HOME — need at least ${MIN_FREE_GB}G (set MIN_FREE_GB to override)"
  fi
  ok "${free}G free on $DIGIT_HOME"
}

step2() {
  hdr 2 "${STEP_DESC[step2]}"
  local env="$DIGIT_HOME/.env"
  [ -f "$env" ] || die "$env not found"

  # Generated ONCE and never rotated by this script. MariaDB reads
  # MARIADB_PASSWORD only when it initialises an empty data directory, so
  # changing this value later does not change the database's real credentials —
  # it only stops Matomo being able to log in. Rotation is a documented
  # procedure (ALTER USER inside matomo-db, then console config:set), not an
  # edit here.
  local k v
  for k in MATOMO_DB_PASSWORD MATOMO_DB_ROOT_PASSWORD; do
    if grep -q "^${k}=" "$env" 2>/dev/null; then
      ok "$k already set (left alone)"
    else
      # `tr -dc … </dev/urandom | head -c 24` is the obvious one-liner and it is
      # wrong here: head closes the pipe at 24 bytes, tr dies of SIGPIPE, and
      # under `set -o pipefail` that kills the script with exit 141. Reading a
      # FIXED amount first means every stage sees a finite stream and exits 0.
      v=$(head -c 48 /dev/urandom | base64 | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-24)
      if $DRY_RUN; then sub "would append $k=<generated> to $env"
      else printf '%s=%s\n' "$k" "$v" >> "$env"; ok "$k generated"; fi
      # NOTE: a full ./deploy.sh stores these in OpenBao and rewrites them from
      # there. Values written by this script are .env-only until then, which is
      # fine — the deploy's lineinfile leaves an existing line alone.
    fi
  done

  for k in "MATOMO_PORT=$MATOMO_PORT" "MATOMO_ARCHIVE_INTERVAL=$MATOMO_ARCHIVE_INTERVAL"; do
    if grep -q "^${k%%=*}=" "$env" 2>/dev/null; then ok "${k%%=*} already set"
    elif $DRY_RUN; then sub "would append $k to $env"
    else printf '%s\n' "$k" >> "$env"; ok "${k%%=*} set"; fi
  done
}

step3() {
  hdr 3 "${STEP_DESC[step3]}"
  local cf; cf=$(compose_files)
  sub "compose files: $cf"
  # Name the three services explicitly rather than a bare `up -d`: this script
  # must not restart anything on the platform side.
  if $DRY_RUN; then
    sub "would run: COMPOSE_PROFILES=matomo docker compose $cf up -d matomo-db matomo matomo-archiver"
  else
    ( cd "$DIGIT_HOME" && COMPOSE_PROFILES=matomo docker compose $cf up -d matomo-db matomo matomo-archiver )
    ok "containers started"
  fi

  $DRY_RUN && return 0
  local i
  for i in $(seq 1 60); do
    if curl -fsS -o /dev/null "http://127.0.0.1:$MATOMO_PORT/" 2>/dev/null; then
      ok "matomo answering on 127.0.0.1:$MATOMO_PORT"; return 0
    fi
    sleep 2
  done
  die "matomo did not answer on 127.0.0.1:$MATOMO_PORT within 120s — check: docker logs digit-matomo"
}

# Is Matomo installed? NOT `test -f config.ini.php`: the image writes that on
# first boot with only [General] installation_first_accessed in it. The
# [database] section is what the installer's database step adds.
matomo_installed() {
  docker exec digit-matomo grep -q '^\[database\]' /var/www/html/config/config.ini.php 2>/dev/null
}

step4() {
  hdr 4 "${STEP_DESC[step4]}"
  if $DRY_RUN; then sub "would check whether matomo is installed"; return 0; fi
  if matomo_installed; then ok "matomo is installed"; return 0; fi

  # This gate is deliberate. Matomo's installer creates the SUPERUSER account,
  # and nothing automated should be choosing that password — so the official
  # matomo:5-apache image has no unattended-install path and we do not fake one.
  # (The k8s tier's Bitnami chart does install unattended; see
  # devops/deploy-as-code/charts/backbone-services/matomo.)
  warn "Matomo is not installed yet — this is the one manual step."
  echo
  sub "1. From your workstation, tunnel to it (it is bound to loopback on purpose):"
  sub "     ssh -L $MATOMO_PORT:127.0.0.1:$MATOMO_PORT <this-host>"
  sub "2. Open http://127.0.0.1:$MATOMO_PORT/ and work through the 8 steps."
  sub "     Database fields arrive pre-filled from the container — leave them."
  sub "     Website URL: clear the field FIRST; it is pre-filled with 'https://'"
  sub "     and typing over it produces 'http://hosthttps://'."
  sub "     Step 7 (JavaScript Tracking Code): SKIP IT. Do not copy the snippet."
  sub "     The portal's analytics shim already does that job plus PII scrubbing;"
  sub "     pasting it creates a second tracker and doubles every count."
  sub "     Note the Site ID (normally 1) — you need it in the configurator."
  sub "3. Then re-run:  $0 --from step5"
  echo
  exit 3
}

step5() {
  hdr 5 "${STEP_DESC[step5]}"
  if $DRY_RUN; then sub "would apply trusted_hosts + proxy_client_headers"; return 0; fi
  matomo_installed || { warn "not installed yet — skipping (see step 4)"; return 0; }

  local cfg=/var/www/html/config/config.ini.php changed=0

  # POSITIONAL 'Section.key[]=<json>' form. `config:set --help` is explicit that
  # the --section/--key/--value form "cannot append to arrays", and both of
  # these ARE arrays — the option form is accepted and writes nothing useful.
  # grep first, because []= APPENDS: an unguarded re-run duplicates the entry.
  if docker exec digit-matomo grep -q 'trusted_hosts\[\] *= *"matomo"' "$cfg"; then
    ok "trusted_hosts already contains 'matomo'"
  else
    # The archiver calls core:archive --url=http://matomo/ over the docker
    # network. Measured: archiving works even with an untrusted --url, because
    # this image archives via CliMulti subprocesses that make no HTTP request.
    # This matters only on the fallback path, where exec() is unavailable and
    # CliMulti fetches index.php over HTTP into the API's trusted-host check.
    docker exec digit-matomo php /var/www/html/console config:set 'General.trusted_hosts[]="matomo"' >/dev/null
    ok "trusted_hosts += matomo"; changed=1
  fi

  if docker exec digit-matomo grep -q 'proxy_client_headers\[\] *= *"HTTP_X_FORWARDED_FOR"' "$cfg"; then
    ok "proxy_client_headers already set"
  else
    # Tracking arrives through the host nginx, so Matomo's default REMOTE_ADDR
    # is nginx itself: every visit would land on one IP, geolocation would show
    # a single city, and "anonymise visitor IP" would have nothing to anonymise.
    docker exec digit-matomo php /var/www/html/console config:set 'General.proxy_client_headers[]="HTTP_X_FORWARDED_FOR"' >/dev/null
    ok "proxy_client_headers += HTTP_X_FORWARDED_FOR"; changed=1
  fi

  [ "$changed" -eq 1 ] && run docker exec digit-matomo php /var/www/html/console cache:clear >/dev/null 2>&1
  return 0
}

step6() {
  hdr 6 "${STEP_DESC[step6]}"
  if $DRY_RUN; then sub "would verify endpoints + archiver + nginx"; return 0; fi
  local problems=0

  local c; c=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$MATOMO_PORT/" || true)
  [ "$c" = "200" ] && ok "matomo admin UI: $c" || { fail "matomo admin UI: $c"; problems=1; }

  # Through the host nginx, same-origin — this is exactly what the browser will
  # fetch. Check the CONTENT TYPE, not just the status: the interesting failure
  # here returns 200.
  local ct; ct=$(curl -s -o /dev/null -w '%{http_code} %{content_type}' "http://localhost/matomo/matomo.js" || true)
  case "$ct" in
    200*javascript*|200*ecmascript*)
      ok "nginx /matomo/matomo.js: $ct" ;;
    200*html*)
      # THE quiet one. With nginx_features.matomo off there is no exact-match
      # block for this path, so it falls through to the SPA location, whose
      # try_files ends at /digit-ui/index.html — nginx answers 200 with the
      # HTML shell. Nothing looks broken; the browser just tries to execute
      # HTML as JavaScript. This is why the portal's analytics shim checks the
      # content type before running, and why it must be checked here too.
      fail "nginx /matomo/matomo.js: $ct — that is the SPA shell, not Matomo."
      sub "nginx_features.matomo is off for this tenant, so the path falls"
      sub "through to the digit-ui try_files fallback. Set nginx_features.matomo"
      sub "AND enable_matomo in host_vars, then re-run ./deploy.sh <tenant>."
      problems=1 ;;
    404*)
      fail "nginx /matomo/matomo.js: 404 — no matomo block and no SPA fallback on this vhost."
      sub "Set nginx_features.matomo (and enable_matomo) and re-run ./deploy.sh <tenant>."
      problems=1 ;;
    502*|503*)
      fail "nginx /matomo/matomo.js: $ct — nginx matched a proxy it cannot reach."
      sub "Either the matomo block is live but nothing listens on $MATOMO_PORT"
      sub "(check MATOMO_PORT vs upstream_matomo_port), or the block is absent and"
      sub "the fallthrough upstream — digit-ui or kong — is itself down."
      problems=1 ;;
    *)
      warn "nginx /matomo/matomo.js: $ct (unexpected)"; problems=1 ;;
  esac

  if docker ps --format '{{.Names}}' | grep -qx digit-matomo-archiver; then
    ok "archiver running (every ${MATOMO_ARCHIVE_INTERVAL}s)"
    # One failed pass is normal before install; a steady stream is not.
    if docker logs --tail 20 digit-matomo-archiver 2>&1 | grep -qi "could not open input file"; then
      warn "archiver logged 'could not open input file' — normal on the first pass only"
    fi
  else
    fail "archiver not running"; problems=1
  fi

  if matomo_installed; then ok "matomo installed"
  else warn "matomo NOT installed — run step4"; problems=1; fi

  echo
  if [ "$problems" -eq 0 ]; then
    printf '%sMatomo is up.%s Next, point the portal at it — this is MDMS, not a redeploy:\n' "$C_OK" "$C_OFF"
    sub "configurator → System → Analytics Providers → Add destination"
    sub "  Provider     MATOMO"
    sub "  Script URL   /matomo/matomo.js      (a PATH, not a URL: same-origin,"
    sub "  Endpoint URL /matomo/matomo.php      needs no TLS and no host allowlist)"
    sub "  Site ID      1"
    sub "Nothing is sent until you tick Enabled there."
    sub "Reading reports: set the date picker to TODAY. The installer leaves"
    sub "date=yesterday, so a working setup reads 'no data' until you change it."
  else
    printf '%sFinished with %s problem(s) above.%s\n' "$C_WARN" "$problems" "$C_OFF"
    exit 1
  fi
}

# ── arg parsing ──────────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --help|-h) usage; exit 0 ;;
    --list)    for s in "${STEPS[@]}"; do printf '%-7s %s\n' "$s" "${STEP_DESC[$s]}"; done; exit 0 ;;
    --dry-run) DRY_RUN=true ;;
    --from)    FROM="$2"; shift ;;
    --to)      TO="$2";   shift ;;
    --only)    ONLY="$2"; shift ;;
    *) die "unknown argument: $1 (try --help)" ;;
  esac
  shift
done

selected() {
  local s="$1"
  if [ -n "$ONLY" ]; then case ",$ONLY," in *",$s,"*) return 0 ;; *) return 1 ;; esac; fi
  local started=true ended=false i
  [ -n "$FROM" ] && started=false
  for i in "${STEPS[@]}"; do
    [ "$i" = "$FROM" ] && started=true
    if [ "$i" = "$s" ]; then $started && ! $ended && return 0 || return 1; fi
    [ "$i" = "$TO" ] && ended=true
  done
  return 1
}

$DRY_RUN && printf '%s(dry run — nothing will be changed)%s\n' "$C_WARN" "$C_OFF"
# `selected "$s" && "$s"` would leave the loop's status at 1 whenever the LAST
# step is filtered out (e.g. --only step2), so a fully successful run exited 1.
for s in "${STEPS[@]}"; do if selected "$s"; then "$s"; fi; done
