#!/bin/bash
# Single entrypoint for DIGIT production deploys.
#
#   ./deploy.sh mytenant              # full deploy
#   ./deploy.sh mytenant --tags=nginx # subset
#   ./deploy.sh mytenant --check      # dry-run + diff
#
# Tenants are defined in inventory/host_vars/<name>.yml. The inventory
# (inventory/hosts.yml) is regenerated on every run from whatever
# host_vars files exist on disk — so adding a new tenant means just
# creating a new file in host_vars/, no manual inventory edits.
#
# This script intentionally has no per-tenant logic. The HMR-pre-check
# lives as a pre_task inside the playbook, so it's tenant-agnostic.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Fail fast with an actionable message if ansible isn't on PATH. Otherwise the
# ansible-playbook call at the end dies with a cryptic "command not found" and
# the operator has no idea why. Common macOS trap: `pip3 install --user ansible`
# puts ansible-playbook in the Python user-base bin, which macOS does NOT add
# to PATH — pip "succeeds" yet the binary is invisible.
if ! command -v ansible-playbook >/dev/null 2>&1; then
  echo "ERROR: 'ansible-playbook' not found on PATH." >&2
  echo "  Install ansible so it is on PATH, then re-run. Options:" >&2
  echo "    macOS:  brew install ansible" >&2
  echo "    pipx :  python3 -m pip install --user pipx && python3 -m pipx ensurepath && pipx install --include-deps ansible" >&2
  echo "    pip  :  pip3 install --user ansible  AND  export PATH=\"\$(python3 -m site --user-base)/bin:\$PATH\"" >&2
  echo "  Verify: ansible-playbook --version" >&2
  exit 127
fi

# ansible buffers a task's stdout until the task ENDS, so the macOS Rosetta
# converge (10-40min) looks like a dead hang with zero feedback. Tell the
# operator the live escape hatches UP FRONT, before ansible swallows output.
cat >&2 <<'BANNER'
────────────────────────────────────────────────────────────────────────
 DIGIT deploy starting. The macOS converge step is long and ansible shows
 NO output until it finishes. For LIVE progress, in another terminal run:

     tail -f /tmp/mac-stack-up.progress
     watch -n5 "docker ps --format '{{.Names}}\t{{.Status}}' | grep -E 'healthy|Exited|Restart'"

 'attempt N/14 … X/Y up-or-healthy' = converging (wait). 'ABORT — LEAKED
 NETWORK ENDPOINT' = stop, restart the engine, re-run PLAIN (no SKIP_DOWN).
────────────────────────────────────────────────────────────────────────
BANNER

# Regenerate inventory/hosts.yml from whatever host_vars exist on disk.
# Every file (except _example.yml) becomes a host under `digit:`.
# Group-wide vars are static here — matching hosts.yml.example.
TENANTS=$(ls inventory/host_vars/*.yml 2>/dev/null \
  | xargs -n1 basename \
  | sed 's/\.yml$//' \
  | grep -v '^_example$' \
  | sort)
{
  echo "# AUTO-GENERATED by deploy.sh from inventory/host_vars/*.yml — DO NOT EDIT."
  echo "# See inventory/hosts.yml.example for the structure and group-wide vars."
  echo "all:"
  echo "  children:"
  echo "    digit:"
  echo "      hosts:"
  for t in $TENANTS; do
    echo "        ${t}:"
  done
  echo "      vars:"
  echo "        ansible_user: root"
  echo "        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'"
} > inventory/hosts.yml

host="${1:-}"
if [[ -z "$host" ]]; then
  echo "usage: $0 <tenant>  [extra ansible-playbook args...]"
  echo ""
  echo "Available tenants:"
  echo "$TENANTS" | sed 's/^/  /'
  exit 1
fi

if [[ ! -f "inventory/host_vars/${host}.yml" ]]; then
  echo "ERROR: no host_vars for '${host}'."
  echo "Expected: inventory/host_vars/${host}.yml"
  echo "Start from the template:"
  echo "  cp inventory/host_vars/_example.yml inventory/host_vars/${host}.yml"
  exit 1
fi

# Incident-derived config gate — refuses combinations that have actually
# burned us (data-wipe fastpath, KC half-wired, inconsistent mobile rules,
# ...). Runs HERE because real host_vars are gitignored: CI can only ever
# validate fixtures; this is the only spot that sees the operator's config.
# Each failure prints the incident it encodes. SKIP_PREFLIGHT=1 to bypass.
if [[ "${SKIP_PREFLIGHT:-0}" != "1" ]]; then
  if ! python3 ../scripts/preflight.py "inventory/host_vars/${host}.yml"; then
    echo "" >&2
    echo "preflight failed — fix the config or re-run with SKIP_PREFLIGHT=1 if you are CERTAIN." >&2
    exit 1
  fi
fi

shift
ansible-playbook \
  -i inventory/hosts.yml \
  --limit "$host" \
  playbook-deploy.yml \
  "$@"
