#!/bin/bash
# Single entrypoint for DIGIT production deploys.
#
#   ./deploy.sh mytenant              # full deploy
#   ./deploy.sh mytenant --tags=nginx # subset
#   ./deploy.sh mytenant --check      # dry-run + diff
#
# Tenants are defined in inventory/host_vars/<name>.yml. The inventory
# (inventory/hosts.yml) is regenerated on every run from whatever
# host_vars files exist on disk — so adding a new tenant means just
# creating a new file in host_vars/, no manual inventory edits.
#
# This script intentionally has no per-tenant logic. The HMR-pre-check
# lives as a pre_task inside the playbook, so it's tenant-agnostic.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# Regenerate inventory/hosts.yml from whatever host_vars exist on disk.
# Every file (except _example.yml) becomes a host under `digit:`.
# Group-wide vars are static here — matching hosts.yml.example.
TENANTS=$(ls inventory/host_vars/*.yml 2>/dev/null \
  | xargs -n1 basename \
  | sed 's/\.yml$//' \
  | grep -v '^_example$' \
  | sort)
{
  echo "# AUTO-GENERATED by deploy.sh from inventory/host_vars/*.yml — DO NOT EDIT."
  echo "# See inventory/hosts.yml.example for the structure and group-wide vars."
  echo "all:"
  echo "  children:"
  echo "    digit:"
  echo "      hosts:"
  for t in $TENANTS; do
    echo "        ${t}:"
  done
  echo "      vars:"
  echo "        ansible_user: root"
  echo "        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'"
} > inventory/hosts.yml

host="${1:-}"
if [[ -z "$host" ]]; then
  echo "usage: $0 <tenant>  [extra ansible-playbook args...]"
  echo ""
  echo "Available tenants:"
  echo "$TENANTS" | sed 's/^/  /'
  exit 1
fi

if [[ ! -f "inventory/host_vars/${host}.yml" ]]; then
  echo "ERROR: no host_vars for '${host}'."
  echo "Expected: inventory/host_vars/${host}.yml"
  echo "Start from the template:"
  echo "  cp inventory/host_vars/_example.yml inventory/host_vars/${host}.yml"
  exit 1
fi

shift
ansible-playbook \
  -i inventory/hosts.yml \
  --limit "$host" \
  playbook-deploy.yml \
  "$@"
