{{- with index .Values "secrets" "minio" }}
{{- if index . "password" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
type: Opaque
data:
  rootUser: {{ .username | b64enc | quote }}
  rootPassword: {{ .password | b64enc | quote }}
{{- end }}
{{- end }}
