#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  run-playwright.sh --target bomet-live|bomet-snapshot|bomet-clone|8c|nairobi-live [options]

Options:
  --suite functional|benchmark|all  Select browser coverage (live default:
                                    functional; disposable default: all)
  --fixture auto|on|off             Seed/teardown the MV corpus (disposable
                                    default: on; live default: off)
  --tier 3k|50k|100k|existing       Dataset label (live default: existing;
                                    disposable default: 3k)
  --principal full|department|public
  --run-id ID                       3-40 safe characters (generated by default)
  --base-url URL                    Override target URL
  --tenant TENANT                   Override target tenant
  --warmups N                       Discarded server warmups (default: 2)
  --samples N                       Measured cold-context samples (default: 20)
  --headed                          Show Chromium (functional diagnosis only)
  --dry-run                         Print the resolved plan without mutation/run

Required environment for employee runs:
  DIGIT_USERNAME, DIGIT_PASSWORD

Required for a disposable benchmark:
  DASHBOARD_8C_BASE_URL / DASHBOARD_BOMET_CLONE_BASE_URL (or --base-url)
  DASHBOARD_8C_TENANT / DASHBOARD_BOMET_CLONE_TENANT (or --tenant)
  DASHBOARD_TARGET_SHA              SHA actually deployed on the target
  DASHBOARD_TARGET_SSH, or DASHBOARD_TARGET_DOCKER_LOCAL=1 on the Docker host
  DASHBOARD_SCHEDULED_REFRESH_DISABLED=yes
  DASHBOARD_ESCALATION_DISABLED=yes

Fixture-on additionally uses the DB variables documented by fixture.sh and
requires DASHBOARD_FIXTURE_ALLOW_MUTATION=yes. bomet-live and nairobi-live are
protected names and can never use --fixture on. bomet-clone also requires a
DASHBOARD_REFERENCE_ENVIRONMENT manifest captured from Bomet; every unchanged
service image must match it before mutation begins.
EOF
}

die() {
  echo "dashboard runner: $*" >&2
  exit 2
}

TARGET=''
SUITE='auto'
FIXTURE='auto'
TIER='auto'
PRINCIPAL='full'
RUN_ID="dashboard-$(date -u +%Y%m%d-%H%M%S)"
BASE_URL_VALUE=''
TENANT_VALUE=''
WARMUPS=2
SAMPLES=20
HEADED=0
DRY_RUN=false

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --target) [[ "$#" -ge 2 ]] || die '--target requires a value'; TARGET="$2"; shift 2 ;;
    --suite) [[ "$#" -ge 2 ]] || die '--suite requires a value'; SUITE="$2"; shift 2 ;;
    --fixture) [[ "$#" -ge 2 ]] || die '--fixture requires a value'; FIXTURE="$2"; shift 2 ;;
    --tier) [[ "$#" -ge 2 ]] || die '--tier requires a value'; TIER="$2"; shift 2 ;;
    --principal) [[ "$#" -ge 2 ]] || die '--principal requires a value'; PRINCIPAL="$2"; shift 2 ;;
    --run-id) [[ "$#" -ge 2 ]] || die '--run-id requires a value'; RUN_ID="$2"; shift 2 ;;
    --base-url) [[ "$#" -ge 2 ]] || die '--base-url requires a value'; BASE_URL_VALUE="$2"; shift 2 ;;
    --tenant) [[ "$#" -ge 2 ]] || die '--tenant requires a value'; TENANT_VALUE="$2"; shift 2 ;;
    --warmups) [[ "$#" -ge 2 ]] || die '--warmups requires a value'; WARMUPS="$2"; shift 2 ;;
    --samples) [[ "$#" -ge 2 ]] || die '--samples requires a value'; SAMPLES="$2"; shift 2 ;;
    --headed) HEADED=1; shift ;;
    --dry-run) DRY_RUN=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

case "${TARGET}" in
  bomet|bomet-live)
    TARGET='bomet-live'
    DEFAULT_BASE_URL='https://bometfeedbackhub.digit.org'
    DEFAULT_TENANT='ke'
    PROTECTED_TARGET=true
    ;;
  nairobi|nairobi-live)
    TARGET='nairobi-live'
    DEFAULT_BASE_URL='https://naipepea.digit.org'
    DEFAULT_TENANT='ke.nairobi'
    PROTECTED_TARGET=true
    ;;
  bomet-snapshot)
    DEFAULT_BASE_URL='https://bometfeedbackhub.digit.org'
    DEFAULT_TENANT='ke'
    PROTECTED_TARGET=false
    ;;
  bomet-clone)
    DEFAULT_BASE_URL="${DASHBOARD_BOMET_CLONE_BASE_URL:-}"
    DEFAULT_TENANT="${DASHBOARD_BOMET_CLONE_TENANT:-}"
    PROTECTED_TARGET=false
    ;;
  8c)
    DEFAULT_BASE_URL="${DASHBOARD_8C_BASE_URL:-}"
    DEFAULT_TENANT="${DASHBOARD_8C_TENANT:-}"
    PROTECTED_TARGET=false
    ;;
  *) die '--target must be bomet-live, bomet-snapshot, bomet-clone, 8c, or nairobi-live' ;;
esac

if [[ "${SUITE}" == 'auto' ]]; then
  if [[ "${PROTECTED_TARGET}" == true ]]; then SUITE='functional'; else SUITE='all'; fi
fi
if [[ "${TIER}" == 'auto' ]]; then
  if [[ "${PROTECTED_TARGET}" == true ]]; then TIER='existing'; else TIER='3k'; fi
fi

BASE_URL_VALUE="${BASE_URL_VALUE:-${DEFAULT_BASE_URL}}"
TENANT_VALUE="${TENANT_VALUE:-${DEFAULT_TENANT}}"
[[ -n "${BASE_URL_VALUE}" ]] || die "set --base-url or the target-specific base URL for ${TARGET}"
[[ -n "${TENANT_VALUE}" ]] || die "set --tenant or the target-specific tenant for ${TARGET}"
[[ "${RUN_ID}" =~ ^[A-Za-z0-9][A-Za-z0-9_-]{2,39}$ ]] || die '--run-id must be 3-40 letters, numbers, underscores, or hyphens'
[[ "${WARMUPS}" =~ ^[0-9]+$ ]] || die '--warmups must be a non-negative integer'
[[ "${SAMPLES}" =~ ^[1-9][0-9]*$ ]] || die '--samples must be a positive integer'
case "${TIER}" in 3k|50k|100k|existing) ;; *) die '--tier must be 3k, 50k, 100k, or existing' ;; esac
case "${SUITE}" in functional|benchmark|all) ;; *) die '--suite must be functional, benchmark, or all' ;; esac
case "${PRINCIPAL}" in full|department|public) ;; *) die '--principal must be full, department, or public' ;; esac
case "${FIXTURE}" in auto|on|off) ;; *) die '--fixture must be auto, on, or off' ;; esac

if [[ "${FIXTURE}" == 'auto' ]]; then
  if [[ "${PROTECTED_TARGET}" == true ]]; then FIXTURE='off'; else FIXTURE='on'; fi
fi
if [[ "${FIXTURE}" == 'on' && "${TIER}" == 'existing' ]]; then
  die '--tier existing requires --fixture off'
fi
if [[ "${SUITE}" != 'functional' && "${FIXTURE}" == 'off' && "${TIER}" != 'existing' && "${DASHBOARD_DATASET_VERIFIED:-}" != 'yes' ]]; then
  die 'an exact benchmark with --fixture off requires DASHBOARD_DATASET_VERIFIED=yes and external fixture evidence'
fi
if [[ "${PROTECTED_TARGET}" == true && "${FIXTURE}" == 'on' ]]; then
  die "refusing to seed protected target ${TARGET}; use the disposable 8c stack"
fi
if [[ "${PROTECTED_TARGET}" == true && "${TIER}" != 'existing' ]]; then
  die "${TARGET} may only use --tier existing; exact tiers belong on a disposable clone"
fi
if [[ "${SUITE}" != 'functional' && "${PROTECTED_TARGET}" == false && -z "${DASHBOARD_TARGET_SHA:-}" ]]; then
  die 'DASHBOARD_TARGET_SHA must identify the candidate build on a disposable benchmark target'
fi
if [[ "${TARGET}" == 'bomet-clone' && -z "${DASHBOARD_REFERENCE_ENVIRONMENT:-}" ]]; then
  die 'bomet-clone requires DASHBOARD_REFERENCE_ENVIRONMENT captured from bomet-live'
fi
if [[ "${TARGET}" == 'bomet-snapshot' ]]; then
  [[ "${BOMET_SNAPSHOT_ACTIVE:-}" == 'yes' ]] || die 'bomet-snapshot must be invoked through run-bomet-snapshot.sh'
  [[ -n "${DASHBOARD_DB_SSH:-}" ]] || die 'bomet-snapshot requires DASHBOARD_DB_SSH'
  [[ "${DASHBOARD_DB_NAME:-}" =~ ^dashboard_perf_[A-Za-z0-9_]+$ ]] || die 'bomet-snapshot requires a disposable dashboard_perf_* database'
fi
if [[ "${FIXTURE}" == 'on' && "${DASHBOARD_SCHEDULED_REFRESH_DISABLED:-}" != 'yes' ]]; then
  die 'benchmark fixture requires DASHBOARD_SCHEDULED_REFRESH_DISABLED=yes after disabling the scheduled MV refresh'
fi
if [[ "${FIXTURE}" == 'on' && "${DASHBOARD_ESCALATION_DISABLED:-}" != 'yes' ]]; then
  die 'fixture-on requires DASHBOARD_ESCALATION_DISABLED=yes after disabling PGR auto-escalation'
fi
if [[ "${PRINCIPAL}" != 'public' ]]; then
  [[ -n "${DIGIT_USERNAME:-}" ]] || die 'DIGIT_USERNAME is required for employee principals'
  [[ -n "${DIGIT_PASSWORD:-}" ]] || die 'DIGIT_PASSWORD is required for employee principals'
fi
if [[ "${FIXTURE}" == 'on' && "${DASHBOARD_FIXTURE_ALLOW_MUTATION:-}" != 'yes' ]]; then
  die 'fixture-on requires DASHBOARD_FIXTURE_ALLOW_MUTATION=yes'
fi

RESULTS_DIR="${REPO_DIR}/performance/results/dashboard-runs/${RUN_ID}-${TARGET}-${TIER}-${PRINCIPAL}"
export BASE_URL="${BASE_URL_VALUE}"
export DIGIT_TENANT="${TENANT_VALUE}"
export DASHBOARD_TARGET="${TARGET}"
export DASHBOARD_TARGET_SHA="${DASHBOARD_TARGET_SHA:-unknown}"
export DASHBOARD_SUITE="${SUITE}"
export DASHBOARD_PRINCIPAL="${PRINCIPAL}"
export DASHBOARD_WARMUPS="${WARMUPS}"
export DASHBOARD_SAMPLES="${SAMPLES}"
export DASHBOARD_HEADED="${HEADED}"
export DASHBOARD_RESULTS_DIR="${RESULTS_DIR}"
export RUN_ID
export DATASET_TIER="${TIER}"

echo "Dashboard run plan"
echo "  target: ${TARGET} (${BASE_URL})"
echo "  tenant/principal: ${DIGIT_TENANT} / ${PRINCIPAL}"
echo "  suite: ${SUITE}; fixture: ${FIXTURE}; tier: ${TIER}"
echo "  warmups/samples: ${WARMUPS}/${SAMPLES}"
echo "  results: ${RESULTS_DIR}"

if [[ "${DRY_RUN}" == true ]]; then exit 0; fi

mkdir -p "${RESULTS_DIR}"
{
  printf 'RUN_ID=%q\n' "${RUN_ID}"
  printf 'TARGET=%q\n' "${TARGET}"
  printf 'BASE_URL=%q\n' "${BASE_URL}"
  printf 'TENANT=%q\n' "${DIGIT_TENANT}"
  printf 'PRINCIPAL=%q\n' "${PRINCIPAL}"
  printf 'TIER=%q\n' "${TIER}"
  printf 'SUITE=%q\n' "${SUITE}"
  printf 'FIXTURE=%q\n' "${FIXTURE}"
  printf 'TARGET_SHA=%q\n' "${DASHBOARD_TARGET_SHA}"
  printf 'REFERENCE_ENVIRONMENT=%q\n' "${DASHBOARD_REFERENCE_ENVIRONMENT:-none}"
  printf 'BOMET_REQUIRE_HOST_MATCH=%q\n' "${DASHBOARD_BOMET_REQUIRE_HOST_MATCH:-yes}"
  printf 'BOMET_CHECK_CONFIG=%q\n' "${DASHBOARD_BOMET_CHECK_CONFIG:-yes}"
  printf 'BOMET_ALLOWED_IMAGE_DRIFT=%q\n' "${DASHBOARD_BOMET_ALLOWED_IMAGE_DRIFT:-pgr-services,digit-ui}"
  printf 'BOMET_ALLOWED_CONFIG_DRIFT=%q\n' "${DASHBOARD_BOMET_ALLOWED_CONFIG_DRIFT:-pgr-services}"
  printf 'BACKGROUND_MODE=%q\n' "${DASHBOARD_BACKGROUND_MODE:-full-stack}"
  printf 'SCHEDULED_REFRESH_DISABLED=%q\n' "${DASHBOARD_SCHEDULED_REFRESH_DISABLED:-no}"
  printf 'ESCALATION_DISABLED=%q\n' "${DASHBOARD_ESCALATION_DISABLED:-no}"
  printf 'HARNESS_SHA=%q\n' "$(git -C "${REPO_DIR}" rev-parse HEAD)"
  [[ -x "${REPO_DIR}/tests/integration-tests/node_modules/.bin/playwright" ]] || \
    die "dependencies missing; run 'npm ci' in ${REPO_DIR}/tests/integration-tests"
  printf 'PLAYWRIGHT_VERSION=%q\n' "$("${REPO_DIR}/tests/integration-tests/node_modules/.bin/playwright" --version)"
  printf 'WARMUPS=%q\n' "${WARMUPS}"
  printf 'SAMPLES=%q\n' "${SAMPLES}"
} > "${RESULTS_DIR}/run-manifest.env"

if [[ -n "${DASHBOARD_TARGET_SSH:-}" ]]; then
  if [[ "${DASHBOARD_TARGET_DOCKER_SUDO:-}" == '1' ]]; then
    ssh "${DASHBOARD_TARGET_SSH}" 'DASHBOARD_DOCKER_SUDO=1 bash -s -- -' < "${SCRIPT_DIR}/capture-environment.sh" > "${RESULTS_DIR}/environment.json"
  else
    ssh "${DASHBOARD_TARGET_SSH}" 'bash -s -- -' < "${SCRIPT_DIR}/capture-environment.sh" > "${RESULTS_DIR}/environment.json"
  fi
elif [[ "${DASHBOARD_TARGET_DOCKER_LOCAL:-}" == '1' ]]; then
  command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1 || \
    die 'DASHBOARD_TARGET_DOCKER_LOCAL=1 but the local Docker daemon is unavailable'
  "${SCRIPT_DIR}/capture-environment.sh" "${RESULTS_DIR}/environment.json"
elif [[ "${SUITE}" != 'functional' ]]; then
  die 'benchmark requires DASHBOARD_TARGET_SSH or DASHBOARD_TARGET_DOCKER_LOCAL=1 for resource evidence'
else
  echo 'Dashboard runner: Docker resource capture unavailable; continuing functional smoke only.' >&2
fi

if [[ "${TARGET}" == 'bomet-clone' ]]; then
  [[ -f "${DASHBOARD_REFERENCE_ENVIRONMENT}" ]] || \
    die "Bomet reference manifest not found: ${DASHBOARD_REFERENCE_ENVIRONMENT}"
  compare_args=(
    "${DASHBOARD_REFERENCE_ENVIRONMENT}"
    "${RESULTS_DIR}/environment.json"
    --mode full
    --output "${RESULTS_DIR}/bomet-parity.json"
  )
  if [[ "${DASHBOARD_BOMET_REQUIRE_HOST_MATCH:-yes}" == 'yes' ]]; then
    compare_args+=(--require-host-match)
  fi
  if [[ "${DASHBOARD_BOMET_CHECK_CONFIG:-yes}" == 'yes' ]]; then
    compare_args+=(--check-config)
    IFS=',' read -r -a allowed_config_drift <<< "${DASHBOARD_BOMET_ALLOWED_CONFIG_DRIFT:-pgr-services}"
    for service in "${allowed_config_drift[@]}"; do
      [[ -n "${service}" ]] && compare_args+=(--allow-config-drift "${service}")
    done
  fi
  IFS=',' read -r -a allowed_image_drift <<< "${DASHBOARD_BOMET_ALLOWED_IMAGE_DRIFT:-pgr-services,digit-ui}"
  for service in "${allowed_image_drift[@]}"; do
    [[ -n "${service}" ]] && compare_args+=(--allow-image-drift "${service}")
  done
  node "${SCRIPT_DIR}/compare-environments.mjs" "${compare_args[@]}" || \
    die 'bomet-clone does not match the Bomet reference manifest'
fi

if [[ "${FIXTURE}" == 'on' ]]; then
  jq -e '
    any(.containers[];
      .service == "pgr-services" and
      (.benchmarkSettings | index("PGR_DASHBOARD_REFRESH_ENABLED=false")) != null and
      (.benchmarkSettings | index("PGR_ESCALATION_ENABLED=false")) != null
    )
  ' "${RESULTS_DIR}/environment.json" >/dev/null || \
    die 'target pgr-services must explicitly set PGR_DASHBOARD_REFRESH_ENABLED=false and PGR_ESCALATION_ENABLED=false'
fi

CHILD=("${SCRIPT_DIR}/run-playwright-child.sh")
if [[ "${FIXTURE}" == 'on' ]]; then
  set +e
  "${SCRIPT_DIR}/fixture.sh" with-fixture \
    --run-id "${RUN_ID}" \
    --tier "${TIER}" \
    --tenant "${TENANT_VALUE}" \
    -- "${CHILD[@]}"
  run_exit=$?
  set -e
  for phase in setup teardown; do
    source_path="${REPO_DIR}/performance/results/dashboard-fixtures/${RUN_ID}-${phase}.json"
    if [[ -f "${source_path}" ]]; then cp "${source_path}" "${RESULTS_DIR}/fixture-${phase}.json"; fi
  done
  exit "${run_exit}"
else
  "${CHILD[@]}"
fi
