apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digit-mcp.fullname" . }}
  labels:
    {{- include "digit-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
