import type { SchemaDescriptor } from './types';

/**
 * Descriptor for `common-masters.ThemeConfig` — v3 designer-1:1 shape.
 *
 * Mirrors the "Theme System" spreadsheet's New System / Nairobi Theme tabs
 * 1:1: every role the designer exposes is its own form input. The runtime
 * counterpart (theflywheel/digit-ui-esbuild applyTheme.js V3_EXPANSION)
 * fans each input out to the CSS vars that actually render it — both
 * existing legacy vars where a role already had one, and the new
 * `--color-<role>` vars introduced for granular roles (button hover,
 * input focus, sidebar selected, status text/border/bg, table hover/
 * selected, etc.).
 *
 * Legacy v1 records continue to render correctly via the unchanged Pass 1
 * flatten. v2 records via Pass 2 SEMANTIC_EXPANSION. This descriptor only
 * shapes the form; existing records can be re-saved through it to migrate
 * to v3.
 *
 * Helper text describes the *visible surface* each token controls so an
 * admin doesn't need the underlying CSS-var taxonomy.
 */
export const themeConfigDescriptor: SchemaDescriptor = {
  schema: 'common-masters.ThemeConfig',
  customEditor: 'theme-config',
  groups: [
    { title: 'Identity', fields: ['code', 'name', 'version'] },

    { title: 'Brand & Surface', fields: [
      'colors.primary-1',
      'colors.primary-2',
      'colors.primary-1-bg',
      'colors.primary-2-bg',
      'colors.page-bg',
      'colors.page-secondary-bg',
      'colors.card-border',
      'colors.card-divider',
    ] },

    { title: 'Text', fields: [
      'colors.text-heading',
      'colors.text-primary',
      'colors.text-secondary',
      'colors.text-disabled',
    ] },

    { title: 'Buttons', fields: [
      'colors.button-primary-bg-default',
      'colors.button-primary-bg-hover',
      'colors.button-primary-bg-pressed',
      'colors.button-primary-text',
      'colors.button-primary-border',
      'colors.button-primary-disabled-bg',
      'colors.button-primary-disabled-text',
      'colors.button-secondary-bg-default',
      'colors.button-secondary-bg-hover',
      'colors.button-secondary-bg-pressed',
      'colors.button-secondary-text',
      'colors.button-secondary-border',
      'colors.button-tertiary-text',
    ] },

    { title: 'Inputs', fields: [
      'colors.input-bg',
      'colors.input-border-default',
      'colors.input-border-focus',
      'colors.input-border-error',
      'colors.input-placeholder',
      'colors.input-text',
      'colors.input-label',
      'colors.input-helper',
    ] },

    { title: 'Header & Sidebar', fields: [
      'colors.header-bg',
      'colors.header-text',
      'colors.header-icon',
      'colors.sidebar-bg',
      'colors.sidebar-text-active',
      'colors.sidebar-text-default',
      'colors.sidebar-hover-text',
      'colors.sidebar-hover-bg',
      'colors.sidebar-icon-active',
      'colors.sidebar-selected-bg',
      'colors.sidebar-selected-text',
    ] },

    { title: 'Status', fields: [
      'colors.status-success-text',
      'colors.status-success-bg',
      'colors.status-success-border',
      'colors.status-error-text',
      'colors.status-error-bg',
      'colors.status-error-border',
      'colors.status-warning-text',
      'colors.status-warning-bg',
      'colors.status-warning-border',
      'colors.status-info-text',
      'colors.status-info-bg',
      'colors.status-info-border',
      'colors.card-success',
      'colors.card-error',
    ] },

    { title: 'Tables & Misc', fields: [
      'colors.table-header-bg',
      'colors.table-header-text',
      'colors.table-row-bg',
      'colors.table-alt-row',
      'colors.table-row-text',
      'colors.table-border',
      'colors.table-hover',
      'colors.table-selected',
      'colors.table-hover-text',
      'colors.table-selected-text',
      'colors.loader',
      'colors.progress',
      'colors.tooltip-bg',
      'colors.tooltip-text',
    ] },

    { title: 'Charts', fields: [
      'colors.chart-1',
      'colors.chart-2',
      'colors.chart-3',
      'colors.chart-4',
      'colors.chart-5',
    ] },
  ],
  fields: [
    // ── Identity ────────────────────────────────────────────────────────────
    { path: 'code', widget: 'text', required: true,
      help: 'Unique theme identifier, e.g. "kenya-green". Used as the MDMS record key.' },
    { path: 'name', widget: 'text',
      help: 'Human-readable theme name shown in admin UIs.' },
    { path: 'version', widget: 'text',
      help: 'Schema version — set to "3" for new themes following the designer 1:1 spec.' },

    // ── Brand & Surface ─────────────────────────────────────────────────────
    { path: 'colors.primary-1', widget: 'color', label: 'Primary 1',
      help: 'Dominant brand color — header/sidebar background, headings, anchor links, button-primary text-on-fill, focused input ring. Often the more saturated of the two brand colors (e.g. dark green on Nairobi).' },
    { path: 'colors.primary-2', widget: 'color', label: 'Primary 2',
      help: 'Accent brand color — primary button background, focus highlights, active sidebar pill. Pairs with Primary 1 (e.g. amber on Nairobi).' },
    { path: 'colors.primary-1-bg', widget: 'color', label: 'Primary 1 bg',
      help: 'Soft tint of Primary 1 — used as table-row hover/selected, sidebar hover background, selection highlights.' },
    { path: 'colors.primary-2-bg', widget: 'color', label: 'Primary 2 bg',
      help: 'Soft tint of Primary 2 — alternate selection wash.' },
    { path: 'colors.page-bg', widget: 'color', label: 'Page background',
      help: 'Main app background (paper white). Cards, secondary-button background, table rows sit on this.' },
    { path: 'colors.page-secondary-bg', widget: 'color', label: 'Page secondary background',
      help: 'Subtle off-white for zebra rows, alternate panel surfaces, disabled-input fill.' },
    { path: 'colors.card-border', widget: 'color', label: 'Card border',
      help: 'Hairline around cards, panels, popovers.' },
    { path: 'colors.card-divider', widget: 'color', label: 'Card divider',
      help: 'Inner dividers within cards / sections.' },

    // ── Text ────────────────────────────────────────────────────────────────
    { path: 'colors.text-heading', widget: 'color', label: 'Text / heading',
      help: 'h1–h6 headings, card titles, section headers — strong visual hierarchy.' },
    { path: 'colors.text-primary', widget: 'color', label: 'Text / primary',
      help: 'Default body text — paragraphs, table cells, form values.' },
    { path: 'colors.text-secondary', widget: 'color', label: 'Text / secondary',
      help: 'Supporting text — captions, metadata, subtitles.' },
    { path: 'colors.text-disabled', widget: 'color', label: 'Text / disabled',
      help: 'Inactive text — disabled buttons/inputs, disabled menu items.' },

    // ── Buttons (Primary 7 + Secondary 5 + Tertiary 1 = 13) ────────────────
    { path: 'colors.button-primary-bg-default', widget: 'color', label: 'Primary button / bg default',
      help: 'Resting background of the primary call-to-action button.' },
    { path: 'colors.button-primary-bg-hover', widget: 'color', label: 'Primary button / bg hover',
      help: 'Background when the cursor is over a primary button. Typically a darker shade of bg-default.' },
    { path: 'colors.button-primary-bg-pressed', widget: 'color', label: 'Primary button / bg pressed',
      help: 'Background during the brief active/clicked moment. Even darker than hover.' },
    { path: 'colors.button-primary-text', widget: 'color', label: 'Primary button / text',
      help: 'Text color inside the primary button. Must read against bg-default.' },
    { path: 'colors.button-primary-border', widget: 'color', label: 'Primary button / border',
      help: 'Optional border around the primary button. Often the same as bg-default.' },
    { path: 'colors.button-primary-disabled-bg', widget: 'color', label: 'Primary button / disabled bg',
      help: 'Background when the primary button is inactive.' },
    { path: 'colors.button-primary-disabled-text', widget: 'color', label: 'Primary button / disabled text',
      help: 'Text color when the primary button is inactive.' },
    { path: 'colors.button-secondary-bg-default', widget: 'color', label: 'Secondary button / bg default',
      help: 'Resting background of the secondary (outlined) button. Usually paper white.' },
    { path: 'colors.button-secondary-bg-hover', widget: 'color', label: 'Secondary button / bg hover',
      help: 'Background when hovering the secondary button.' },
    { path: 'colors.button-secondary-bg-pressed', widget: 'color', label: 'Secondary button / bg pressed',
      help: 'Background during the active/clicked moment of the secondary button.' },
    { path: 'colors.button-secondary-text', widget: 'color', label: 'Secondary button / text',
      help: 'Text color inside the secondary button. Usually Primary 1.' },
    { path: 'colors.button-secondary-border', widget: 'color', label: 'Secondary button / border',
      help: 'Border defining the secondary button outline.' },
    { path: 'colors.button-tertiary-text', widget: 'color', label: 'Tertiary / link text',
      help: 'Text-only buttons and links — the most subtle action treatment. Usually Primary 1.' },

    // ── Inputs (8) ──────────────────────────────────────────────────────────
    { path: 'colors.input-bg', widget: 'color', label: 'Input / bg',
      help: 'Background of form input fields, textareas, selects.' },
    { path: 'colors.input-border-default', widget: 'color', label: 'Input / border default',
      help: 'Resting border color of inputs (unfocused, no error).' },
    { path: 'colors.input-border-focus', widget: 'color', label: 'Input / border focus',
      help: 'Border color when an input has keyboard focus. Usually Primary 1 — the brand-aware focus ring.' },
    { path: 'colors.input-border-error', widget: 'color', label: 'Input / border error',
      help: 'Border color when validation fails on an input.' },
    { path: 'colors.input-placeholder', widget: 'color', label: 'Input / placeholder',
      help: 'Placeholder text inside empty inputs.' },
    { path: 'colors.input-text', widget: 'color', label: 'Input / text',
      help: 'Color of user-entered text inside inputs.' },
    { path: 'colors.input-label', widget: 'color', label: 'Input / label',
      help: 'Label text above or beside inputs.' },
    { path: 'colors.input-helper', widget: 'color', label: 'Input / helper',
      help: 'Helper or hint text below inputs.' },

    // ── Header & Sidebar (3 + 8 = 11) ───────────────────────────────────────
    { path: 'colors.header-bg', widget: 'color', label: 'Header / bg',
      help: 'Background of the top navigation bar.' },
    { path: 'colors.header-text', widget: 'color', label: 'Header / text',
      help: 'Text color on the header (titles, actions).' },
    { path: 'colors.header-icon', widget: 'color', label: 'Header / icon',
      help: 'Icon and logo color in the header.' },
    { path: 'colors.sidebar-bg', widget: 'color', label: 'Sidebar / bg',
      help: 'Background of the side navigation rail.' },
    { path: 'colors.sidebar-text-active', widget: 'color', label: 'Sidebar / text active',
      help: 'Text color of the actively-selected navigation item.' },
    { path: 'colors.sidebar-text-default', widget: 'color', label: 'Sidebar / text default',
      help: 'Text color of idle (non-hovered, non-selected) sidebar items.' },
    { path: 'colors.sidebar-hover-text', widget: 'color', label: 'Sidebar / hover text',
      help: 'Text color on a sidebar item being hovered.' },
    { path: 'colors.sidebar-hover-bg', widget: 'color', label: 'Sidebar / hover bg',
      help: 'Background tint shown when hovering a sidebar item.' },
    { path: 'colors.sidebar-icon-active', widget: 'color', label: 'Sidebar / icon active',
      help: 'Icon color on the actively-selected sidebar item.' },
    { path: 'colors.sidebar-selected-bg', widget: 'color', label: 'Sidebar / selected bg',
      help: 'Background of the persistent "selected" pill on the active sidebar item.' },
    { path: 'colors.sidebar-selected-text', widget: 'color', label: 'Sidebar / selected text',
      help: 'Text color inside the selected pill.' },

    // ── Status (4 severities × 3 roles + 2 cards = 14) ──────────────────────
    { path: 'colors.status-success-text', widget: 'color', label: 'Status success / text',
      help: 'Text inside success alerts and badges.' },
    { path: 'colors.status-success-bg', widget: 'color', label: 'Status success / bg',
      help: 'Background fill of success alerts and toasts (soft tint).' },
    { path: 'colors.status-success-border', widget: 'color', label: 'Status success / border',
      help: 'Left-border / outline accent of success alerts.' },
    { path: 'colors.status-error-text', widget: 'color', label: 'Status error / text',
      help: 'Text inside error alerts, validation errors, destructive labels.' },
    { path: 'colors.status-error-bg', widget: 'color', label: 'Status error / bg',
      help: 'Background fill of error alerts and toasts.' },
    { path: 'colors.status-error-border', widget: 'color', label: 'Status error / border',
      help: 'Left-border / outline accent of error alerts.' },
    { path: 'colors.status-warning-text', widget: 'color', label: 'Status warning / text',
      help: 'Text inside warning alerts and badges.' },
    { path: 'colors.status-warning-bg', widget: 'color', label: 'Status warning / bg',
      help: 'Background fill of warning alerts.' },
    { path: 'colors.status-warning-border', widget: 'color', label: 'Status warning / border',
      help: 'Left-border / outline accent of warning alerts.' },
    { path: 'colors.status-info-text', widget: 'color', label: 'Status info / text',
      help: 'Text inside info alerts and neutral-attention badges.' },
    { path: 'colors.status-info-bg', widget: 'color', label: 'Status info / bg',
      help: 'Background fill of info alerts.' },
    { path: 'colors.status-info-border', widget: 'color', label: 'Status info / border',
      help: 'Left-border / outline accent of info alerts.' },
    { path: 'colors.card-success', widget: 'color', label: 'Card / success accent',
      help: 'Accent color on success-state cards (e.g. successfully-resolved complaint card).' },
    { path: 'colors.card-error', widget: 'color', label: 'Card / error accent',
      help: 'Accent color on error-state cards.' },

    // ── Tables & Misc (10 + 4 = 14) ─────────────────────────────────────────
    { path: 'colors.table-header-bg', widget: 'color', label: 'Table / header bg',
      help: 'Background of the table header row.' },
    { path: 'colors.table-header-text', widget: 'color', label: 'Table / header text',
      help: 'Text color in the table header (column titles).' },
    { path: 'colors.table-row-bg', widget: 'color', label: 'Table / row bg',
      help: 'Default body-row background.' },
    { path: 'colors.table-alt-row', widget: 'color', label: 'Table / alt row',
      help: 'Alternate body-row background for zebra striping.' },
    { path: 'colors.table-row-text', widget: 'color', label: 'Table / row text',
      help: 'Text color inside body cells.' },
    { path: 'colors.table-border', widget: 'color', label: 'Table / border',
      help: 'Grid lines between rows / columns.' },
    { path: 'colors.table-hover', widget: 'color', label: 'Table / hover',
      help: 'Background tint when hovering a row.' },
    { path: 'colors.table-selected', widget: 'color', label: 'Table / selected',
      help: 'Background tint of a selected row.' },
    { path: 'colors.table-hover-text', widget: 'color', label: 'Table / hover text',
      help: 'Text color on a hovered row (only meaningful if the hover-bg is dark).' },
    { path: 'colors.table-selected-text', widget: 'color', label: 'Table / selected text',
      help: 'Text color inside the selected row.' },
    { path: 'colors.loader', widget: 'color', label: 'Loader',
      help: 'Color of the loading spinner / progress indicator.' },
    { path: 'colors.progress', widget: 'color', label: 'Progress',
      help: 'Progress-bar fill color.' },
    { path: 'colors.tooltip-bg', widget: 'color', label: 'Tooltip / bg',
      help: 'Background color of tooltips.' },
    { path: 'colors.tooltip-text', widget: 'color', label: 'Tooltip / text',
      help: 'Text color inside tooltips.' },

    // ── Charts (5) ──────────────────────────────────────────────────────────
    { path: 'colors.chart-1', widget: 'color', label: 'Chart 1',
      help: 'First data-series color (bar 1, line 1, pie slice 1).' },
    { path: 'colors.chart-2', widget: 'color', label: 'Chart 2',
      help: 'Second data-series color.' },
    { path: 'colors.chart-3', widget: 'color', label: 'Chart 3',
      help: 'Third data-series color.' },
    { path: 'colors.chart-4', widget: 'color', label: 'Chart 4',
      help: 'Fourth data-series color.' },
    { path: 'colors.chart-5', widget: 'color', label: 'Chart 5',
      help: 'Fifth data-series color.' },
  ],
};
