// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 4c72207bfce17ac017725cde486952b7975012dbc8da8042f193f801dba80c67


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "configurator-blue";

export const themeNames: ThemeName[] = ["configurator-blue"];

export type KcEnvName = "DIGIT_BRAND_BASE_URL" | "DIGIT_APP_NAME";

export const kcEnvNames: KcEnvName[] = ["DIGIT_BRAND_BASE_URL", "DIGIT_APP_NAME"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "DIGIT_BRAND_BASE_URL": "/configurator/brand",
  "DIGIT_APP_NAME": "DIGIT Complaint Management"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL
