import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import WorkspacePage from './WorkspacePage';
import { renameWorkspace, searchWorkspace, invitationPolicy } from './workspace';
vi.mock('@/App', () => ({ useApp: () => ({ state: { tenant: 'acme', user: { roles: ['ACCOUNT_ADMIN', 'MDMS_ADMIN'] } } }) }));
vi.mock('@/onboarding/organisation', () => ({ useOrganisation: () => ({ name: 'Acme', logoUrl: null }), announceOrganisation: vi.fn() }));
vi.mock('@/providers/i18nProvider', () => ({ clearTranslationCache: vi.fn() }));
vi.mock('./workspace', () => ({ searchWorkspace: vi.fn(), renameWorkspace: vi.fn(), invitationPolicy: vi.fn(), saveInvitationPolicy: vi.fn() }));
const view = (version: number, status?: 'PENDING' | 'DONE') => ({ Workspace: { version }, Probes: null, Rename: status ? { id: 'r', name: 'New Name', tenantId: 'acme', version: 4, status, updatedAt: 1 } : null }) as Awaited<ReturnType<typeof searchWorkspace>>;
beforeEach(() => { sessionStorage.clear(); vi.resetAllMocks(); vi.mocked(searchWorkspace).mockResolvedValue(view(3)); vi.mocked(invitationPolicy).mockResolvedValue(null); });
afterEach(() => vi.useRealTimers());
const page = () => render(<MemoryRouter><WorkspacePage /></MemoryRouter>);
it('retains the original request after an ambiguous failure, then waits for publication', async () => {
  vi.mocked(renameWorkspace).mockRejectedValueOnce(new Error('Network unavailable')).mockResolvedValueOnce(view(4, 'PENDING').Rename!);
  const ui = page();
  await waitFor(() => expect(screen.getByRole('button', { name: 'Change workspace name' })).toBeDisabled());
  fireEvent.change(screen.getByRole('textbox', { name: 'Workspace name' }), { target: { value: 'New Name' } });
  fireEvent.click(screen.getByRole('button', { name: 'Change workspace name' }));
  await screen.findByRole('button', { name: 'Retry name change' });
  vi.mocked(searchWorkspace).mockResolvedValue(view(8, 'PENDING'));
  fireEvent.click(screen.getByRole('button', { name: 'Retry name change' }));
  await screen.findByText(/Waiting for publication/);
  expect(vi.mocked(renameWorkspace).mock.calls).toEqual([[{ tenantId: 'acme', version: 3, name: 'New Name' }], [{ tenantId: 'acme', version: 3, name: 'New Name' }]]);
  expect(screen.queryByText('Workspace name updated to New Name.')).not.toBeInTheDocument();
  ui.unmount();
});
it('polls pending publication, uses fresh workspace version for the next rename, and stops on unmount', async () => {
  vi.useFakeTimers();
  vi.mocked(searchWorkspace).mockResolvedValueOnce(view(8, 'PENDING')).mockResolvedValue(view(9, 'DONE'));
  vi.mocked(renameWorkspace).mockResolvedValue({ ...view(10, 'PENDING').Rename!, name: 'Next Name', version: 10 });
  const ui = page();
  await act(async () => {});
  expect(screen.getByText(/Publishing New Name/)).toBeInTheDocument();
  await act(async () => { await vi.advanceTimersByTimeAsync(2000); });
  expect(screen.getByText('Workspace name updated to New Name.')).toBeInTheDocument();
  fireEvent.change(screen.getByRole('textbox', { name: 'Workspace name' }), { target: { value: 'Next Name' } });
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Change workspace name' })); });
  expect(renameWorkspace).toHaveBeenCalledWith({ tenantId: 'acme', name: 'Next Name', version: 9 });
  ui.unmount(); const calls = vi.mocked(searchWorkspace).mock.calls.length;
  await act(async () => { await vi.advanceTimersByTimeAsync(10000); });
  expect(searchWorkspace).toHaveBeenCalledTimes(calls);
});
