// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: acbe54e9b62632241ab2e45223dddfcabf5ae1883f63719664d22d62093a38e3


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "configurator-blue" | "digit-employee";

export const themeNames: ThemeName[] = ["configurator-blue", "digit-employee"];

export type KcEnvName = "DIGIT_BRAND_BASE_URL" | "DIGIT_APP_NAME" | "DIGIT_IDENTITY_BFF_BASE_URL" | "DIGIT_PUBLIC_API_BASE_URL" | "DIGIT_MDMS_SEARCH_PATH" | "DIGIT_UI_CONFIG_MODULE_NAME" | "DIGIT_DEFAULT_LOCALE" | "DIGIT_FOOTER_URL" | "DIGIT_FOOTER_BW_URL" | "DIGIT_HOME_URL";

export const kcEnvNames: KcEnvName[] = ["DIGIT_BRAND_BASE_URL", "DIGIT_APP_NAME", "DIGIT_IDENTITY_BFF_BASE_URL", "DIGIT_PUBLIC_API_BASE_URL", "DIGIT_MDMS_SEARCH_PATH", "DIGIT_UI_CONFIG_MODULE_NAME", "DIGIT_DEFAULT_LOCALE", "DIGIT_FOOTER_URL", "DIGIT_FOOTER_BW_URL", "DIGIT_HOME_URL"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "DIGIT_BRAND_BASE_URL": "/configurator/brand",
  "DIGIT_APP_NAME": "DIGIT Complaint Management",
  "DIGIT_IDENTITY_BFF_BASE_URL": "",
  "DIGIT_PUBLIC_API_BASE_URL": "",
  "DIGIT_MDMS_SEARCH_PATH": "/mdms-v2/v1/_search",
  "DIGIT_UI_CONFIG_MODULE_NAME": "commonMDMSConfig",
  "DIGIT_DEFAULT_LOCALE": "en_IN",
  "DIGIT_FOOTER_URL": "/digit-ui/brand/digit-footer.png",
  "DIGIT_FOOTER_BW_URL": "/digit-ui/brand/digit-footer-bw.png",
  "DIGIT_HOME_URL": "https://www.digit.org/"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL
