#!/usr/bin/env python3
"""The notification defaults pgr-services gives a new workspace are the deploy's own, not a copy that
drifts: backend/pgr-services/src/main/resources/onboarding/notification-defaults.json is generated by
local-setup/scripts/build-onboarding-notification-defaults.py from seed-notifications.py and the
default-data-handler files, and this test fails as soon as it is stale.

Run: python3 -m unittest local-setup/tests/test_onboarding_notification_defaults.py
"""
import importlib.util
import json
import os
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SCRIPTS = os.path.join(REPO, "local-setup", "scripts")


def _load(name, filename):
    spec = importlib.util.spec_from_file_location(name, os.path.join(SCRIPTS, filename))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


build = _load("build_onboarding_notification_defaults", "build-onboarding-notification-defaults.py")
sn = _load("seed_notifications_for_packaging_test", "seed-notifications.py")


class PackagedDefaults(unittest.TestCase):

    def test_the_packaged_file_is_what_the_generator_makes_now(self):
        with open(build.OUT, encoding="utf-8") as fh:
            committed = fh.read()
        self.assertEqual(build.render(build.build()), committed,
                         "stale: run local-setup/scripts/build-onboarding-notification-defaults.py")

    def test_it_carries_the_seeders_access_rows_and_the_shipped_configuration(self):
        doc = build.build()
        by = {}
        for r in doc["records"]:
            by.setdefault(r["schemaCode"], []).append(r["data"])
        self.assertEqual(sorted(a["id"] for a in by[sn.ACTION_SCHEMA]), sorted(a[0] for a in sn.NOTIF_ACTIONS))
        granted = {(ra["rolecode"], ra["actionid"]) for ra in by[sn.ROLEACTION_SCHEMA]}
        wanted = {(role, a[0]) for a in sn.NOTIF_ACTIONS for role in a[6]}
        self.assertEqual(granted, wanted, "every role the seeder grants exists in a workspace")
        ddh = os.path.join(build.DDH, "mdmsData-dev", "NOTIFICATIONS")
        for code in ("NOTIFICATIONS.Template", "NOTIFICATIONS.ProviderTemplate", "NOTIFICATIONS.Routing",
                     "NOTIFICATIONS.EventCatalogue"):
            with open(os.path.join(ddh, code + ".json"), encoding="utf-8") as fh:
                self.assertEqual(by[code], json.load(fh), code)
        self.assertNotIn("NOTIFICATIONS.Channel", by, "channel rows follow the deployment allowlist instead")
        self.assertEqual([s["code"] for s in doc["schemas"]], sn.NOTIF_CODES + sn.NEW_CODES)
        self.assertEqual([r["schemaCode"] for r in doc["records"]][-1], "NOTIFICATIONS.Routing", "routing last")

    def test_check_mode_fails_on_a_stale_file(self):
        original = build.OUT
        stale = os.path.join(HERE, ".stale-notification-defaults.json")
        with open(stale, "w", encoding="utf-8") as fh:
            fh.write("{}\n")
        self.addCleanup(os.remove, stale)
        self.addCleanup(setattr, build, "OUT", original)
        build.OUT = stale
        import contextlib
        import io
        with contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(build.main(["--check"]), 1)


if __name__ == "__main__":
    unittest.main()
