package org.egov.pgr.onboarding;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;
import java.io.IOException;
import java.util.*;

/**
 * The notification defaults a new workspace gets (onboarding step {@value NotificationDefaultsStep#STEP}):
 * {@code onboarding/notification-defaults.json}, GENERATED by
 * {@code local-setup/scripts/build-onboarding-notification-defaults.py} from the very files the deploy's
 * {@code seed-notifications.py} seeds from (its access-control rows, the default-data-handler schemas and
 * {@code mdmsData-dev/NOTIFICATIONS} rows). It is packaged here only because this image's build context
 * cannot reach them; {@code local-setup/tests/test_onboarding_notification_defaults.py} fails when it drifts.
 */
@Component
public class NotificationDefaults {
    static final String RESOURCE = "onboarding/notification-defaults.json";
    private final ObjectMapper mapper;
    private final JsonNode seed;
    private final Map<String, List<String>> unique = new HashMap<>();
    private final Set<String> schemaCodes = new HashSet<>();
    private final Map<String, List<JsonNode>> recordsBySchema = new LinkedHashMap<>();

    public NotificationDefaults(ObjectMapper mapper) throws IOException {
        this.mapper = mapper;
        try (var input = new ClassPathResource(RESOURCE).getInputStream()) { seed = mapper.readTree(input); }
        seed.path("unique").fields().forEachRemaining(e -> {
            List<String> fields = new ArrayList<>();
            e.getValue().forEach(f -> fields.add(f.asText()));
            unique.put(e.getKey(), List.copyOf(fields));
        });
        for (JsonNode schema : seed.path("schemas")) schemaCodes.add(schema.path("code").asText());
        for (JsonNode record : seed.path("records")) {
            String code = record.path("schemaCode").asText();
            if (!unique.containsKey(code) || !record.path("data").isObject()) throw new IOException("Invalid notification defaults: " + code);
            recordsBySchema.computeIfAbsent(code, k -> new ArrayList<>()).add(record);
        }
        if (schemaCodes.isEmpty() || recordsBySchema.isEmpty()) throw new IOException("Empty notification defaults");
    }

    /** Schema definitions ({@code code}, {@code definition}), legacy RAINMAKER-PGR.Notification* and NOTIFICATIONS.*. */
    public JsonNode schemas() { return seed.path("schemas"); }
    /** Seed rows per schema, in write order: access-control rows, then configuration with Routing LAST. */
    public Map<String, List<JsonNode>> recordsBySchema() { return Collections.unmodifiableMap(recordsBySchema); }
    public List<String> unique(String schemaCode) { return unique.getOrDefault(schemaCode, List.of()); }
    public boolean isSchema(String code) { return schemaCodes.contains(code); }
    public Set<String> configurationSchemas() { return texts(seed.path("configurationSchemas")); }
    /** The routing masters, either namespace: a row in one the seed did not write means the tenant has its own configuration. */
    public Set<String> routingSchemas() { return texts(seed.path("routingSchemas")); }

    /** The record's data with {@code {tenantid}} replaced, as it is written. */
    public JsonNode data(JsonNode record, String tenant) {
        try { return mapper.readTree(mapper.writeValueAsString(record.path("data")).replace("{tenantid}", tenant)); }
        catch (IOException e) { throw new IllegalStateException("Invalid notification defaults", e); }
    }

    /** The x-unique values of a row: how MDMS tells two rows of a schema apart. */
    public String key(String schemaCode, JsonNode data) {
        StringJoiner key = new StringJoiner("\u0000");
        for (String field : unique(schemaCode)) key.add(data.path(field).asText());
        return key.toString();
    }

    /** True only for one of the seed's own rows, verbatim, for this tenant: the provisioner writes nothing else in this step. */
    public boolean isSeedRecord(String schemaCode, JsonNode data, String tenant) {
        for (JsonNode record : recordsBySchema.getOrDefault(schemaCode, List.of()))
            if (data(record, tenant).equals(data)) return true;
        return false;
    }

    private static Set<String> texts(JsonNode array) {
        Set<String> out = new LinkedHashSet<>();
        array.forEach(v -> out.add(v.asText()));
        return Collections.unmodifiableSet(out);
    }
}
