import { useMemo, useState } from 'react';
import { useListContext } from 'ra-core';
import { GitMerge, Loader2, Check, X, AlertTriangle, Circle, MinusCircle, ArrowRight, Copy, Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogFooter,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import {
  MIGRATION_STEPS,
  runComplaintHierarchyMigration,
  resolveMigrationTenants,
  type MigrationStepStatus,
  type MigrationResult,
} from '@/api/services/hierarchyMigration';

interface StepState {
  key: string;
  label: string;
  status: MigrationStepStatus;
  detail?: string;
}

const initialSteps = (): StepState[] =>
  MIGRATION_STEPS.map((s) => ({ ...s, status: 'pending' as MigrationStepStatus }));

/**
 * Build a ready-to-run STANDALONE Node migration script, parameterised with the
 * resolved tenant(s). This is a trimmed inline twin of docs/migration/migrate.cjs
 * so an operator can run the exact same migration headless (node/psql tooling)
 * outside the configurator. Keep this logic in lock-step with migrate.cjs and
 * api/services/hierarchyMigration.ts.
 */
function buildStandaloneScript(managing: string, state: string): string {
  const targetsLiteral = JSON.stringify(Array.from(new Set([managing, state].filter(Boolean))));
  // NOTE: this string is intentionally self-contained (no imports beyond core
  // `url`/`http(s)`) so it runs with a bare `node migrate.cjs`.
  return `/* eslint-disable */
// Standalone complaint-hierarchy migration — generated by the configurator for tenant '${managing}'.
// Trimmed twin of docs/migration/migrate.cjs. Idempotent, dual-mode (preserve existing N-level
// tree, else derive flat 2-level from menuPath). Writes interior nodes + leaves into
// RAINMAKER-PGR.ComplaintHierarchy (leaf code = serviceCode verbatim, departments[], slaHours,
// keywords) and seeds COMPLAINT_HIERARCHY.<code> localization for every node.
//
//   BASE_URL=https://your-gateway OAUTH_USER=ADMIN OAUTH_PASS='***' node migrate.cjs
//   # or: BASE_URL=... TOKEN=<authToken> node migrate.cjs   (skips login)
//   # preview only: add DRY_RUN=1
const url = require('url');
const BASE = process.env.BASE_URL;
if (!BASE) { console.error('Set BASE_URL'); process.exit(2); }
const TARGETS = ${targetsLiteral};               // [managing, state] for tenant '${managing}'
const LOGIN_TENANT = ${JSON.stringify(state || managing)};
const HT = process.env.HIERARCHY || ${JSON.stringify('PGR')};
const LOCALE = process.env.LOCALE || 'en_IN';
const DRY_RUN = /^(1|true|yes)$/i.test(String(process.env.DRY_RUN || ''));
const BASIC = process.env.OAUTH_BASIC || 'ZWdvdi11c2VyLWNsaWVudDo=';
const U = new url.URL(BASE);
const http = U.protocol === 'https:' ? require('https') : require('http');
const PORT = U.port || (U.protocol === 'https:' ? 443 : 80);
const HDEF = 'RAINMAKER-PGR.ComplaintHierarchyDefinition', HIER = 'RAINMAKER-PGR.ComplaintHierarchy';
const SD = 'RAINMAKER-PGR.ServiceDefs', NODE = 'RAINMAKER-PGR.ClassificationNode', DEPTS = 'RAINMAKER-PGR.ComplaintTypeDepartments';
const CATEGORY = 'CATEGORY', LEAF = 'SUB_TYPE', SAFE = /^[A-Za-z0-9_.\\-]+$/;
const PASS = '\\u2705', WARN = '\\u26A0\\uFE0F ', FAIL = '\\u274C';
let RI = null;
function req(path, method, headers, body) {
  return new Promise((res) => {
    const r = http.request({ host: U.hostname, port: PORT, path, method, headers }, (s) => {
      let b = ''; s.on('data', (c) => (b += c)); s.on('end', () => res({ code: s.statusCode, body: b }));
    });
    r.on('error', (e) => res({ code: 0, body: String(e) }));
    if (body) r.write(body); r.end();
  });
}
const form = (p, d) => req(p, 'POST', { authorization: 'Basic ' + BASIC, 'content-type': 'application/x-www-form-urlencoded', 'content-length': Buffer.byteLength(d) }, d);
const post = (p, o) => req(p, 'POST', { 'content-type': 'application/json' }, JSON.stringify(o));
async function search(t, schema, opts) {
  opts = opts || {};
  const r = await post('/mdms-v2/v2/_search', { RequestInfo: RI, MdmsCriteria: { tenantId: t, schemaCode: schema, limit: opts.limit || 5000, offset: 0, uniqueIdentifiers: opts.uniqueIdentifiers } });
  try { return { code: r.code, rows: (JSON.parse(r.body).mdms || []).map((m) => m.data) }; } catch { return { code: r.code, rows: null }; }
}
async function searchAcross(ts, schema) { const out = []; for (const t of ts) { const r = await search(t, schema); if (Array.isArray(r.rows)) out.push.apply(out, r.rows); } return out; }
async function create(t, schema, uid, data) {
  const r = await post('/mdms-v2/v2/_create/' + schema, { RequestInfo: RI, Mdms: { tenantId: t, schemaCode: schema, uniqueIdentifier: uid, data, isActive: true } });
  if (r.code >= 200 && r.code < 300) return { ok: true, code: r.code };
  const dup = /DUPLICATE|already exist|ALREADY_EXISTS|unique/i.test(r.body || '');
  return { ok: dup, code: r.code, duplicate: dup, body: r.body };
}
async function upsert(t, messages) {
  if (!messages.length) return; const body = { RequestInfo: Object.assign({}, RI, { apiId: 'emp', action: 'create' }), tenantId: t, locale: LOCALE, messages };
  const r = await post('/localization/messages/v1/_upsert', body);
  if (!(r.code >= 200 && r.code < 300)) { for (const m of messages) { await post('/localization/messages/v1/_upsert', { RequestInfo: Object.assign({}, RI, { apiId: 'emp', action: 'create' }), tenantId: t, locale: LOCALE, messages: [m] }); } }
}
function nodeLoc(code, name) {
  // Key-based labels (COMPLAINT_HIERARCHY.<code>, exact + uppercase) — the
  // runtime resolves complaint labels via this namespace. Mirrors
  // docs/migration/migrate.cjs.
  const out = [], seen = new Set();
  const push = (c, m) => { if (seen.has(c)) return; seen.add(c); out.push({ code: c, message: m, module: 'rainmaker-pgr', locale: LOCALE }); };
  push('COMPLAINT_HIERARCHY.' + code, name); push('COMPLAINT_HIERARCHY.' + code.toUpperCase(), name);
  return out;
}
(async () => {
  let token = process.env.TOKEN;
  if (!token) {
    const d = 'username=' + encodeURIComponent(process.env.OAUTH_USER || 'ADMIN') + '&password=' + encodeURIComponent(process.env.OAUTH_PASS || 'eGov@123') + '&userType=EMPLOYEE&tenantId=' + LOGIN_TENANT + '&scope=read&grant_type=password';
    const r = await form('/user/oauth/token', d); let j; try { j = JSON.parse(r.body); } catch { j = null; }
    if (!j || !j.access_token) { console.log(FAIL + ' Auth failed (HTTP ' + r.code + ')'); process.exit(2); }
    token = j.access_token; const u = j.UserRequest;
    RI = { apiId: 'Rainmaker', ver: '1.0', msgId: 'migrate', authToken: token, userInfo: { id: u.id, uuid: u.uuid, userName: u.userName, name: u.name, type: u.type, roles: u.roles, tenantId: u.tenantId } };
  } else { RI = { apiId: 'Rainmaker', ver: '1.0', msgId: 'migrate', authToken: token, userInfo: { tenantId: LOGIN_TENANT, type: 'EMPLOYEE', roles: [] } }; }
  console.log(PASS + ' Auth OK · tenants=' + TARGETS.join(', ') + (DRY_RUN ? '  [DRY-RUN]' : ''));

  const sdRows = await searchAcross(TARGETS, SD), nodeRows = await searchAcross(TARGETS, NODE), defRows = await searchAcross(TARGETS, HDEF), deptRows = await searchAcross(TARGETS, DEPTS);
  const deptByCode = new Map();
  for (const r of deptRows) { const sc = String(r.serviceCode || '').trim(); if (!sc) continue; deptByCode.set(sc, { departments: Array.isArray(r.departments) ? r.departments.map(String) : [], primary: r.primaryDepartment ? String(r.primaryDepartment) : undefined }); }
  const byCode = new Map();
  for (const r of sdRows) {
    const sc = String(r.serviceCode || '').trim(); if (!sc) continue; const mp = String(r.menuPath || '').trim(); const ex = byCode.get(sc);
    if (!ex || (!ex.menuPath && mp)) {
      const dep = deptByCode.get(sc); const primary = (dep && dep.primary) || (r.department ? String(r.department) : undefined);
      const all = dep && dep.departments && dep.departments.length ? dep.departments : primary ? [primary] : [];
      byCode.set(sc, { serviceCode: sc, name: String(r.name || sc), menuPath: mp, menuPathName: r.menuPathName ? String(r.menuPathName) : undefined, department: primary, departments: all, slaHours: typeof r.slaHours === 'number' ? r.slaHours : Number(r.slaHours) || undefined, keywords: r.keywords ? String(r.keywords) : undefined, order: typeof r.order === 'number' ? r.order : undefined, parentCode: r.parentCode ? String(r.parentCode) : undefined, sector: r.sector ? String(r.sector) : undefined });
    }
  }
  const defs = Array.from(byCode.values());
  if (defs.length === 0) { console.log(WARN + 'No ServiceDefs found. Nothing to migrate.'); process.exit(0); }
  const interiorByCode = new Map();
  for (const n of nodeRows) { if (n.hierarchyType && n.hierarchyType !== HT) continue; const code = String(n.code || '').trim(); if (!code || interiorByCode.has(code)) continue; interiorByCode.set(code, { levelCode: String(n.levelCode || CATEGORY), code, parentCode: n.parentCode != null ? String(n.parentCode) : null, name: String(n.name || code), order: typeof n.order === 'number' ? n.order : undefined, path: n.path ? String(n.path) : undefined }); }
  const existingDef = defRows.find((d) => d.hierarchyType === HT) || defRows[0];
  const preserve = !!(existingDef && Array.isArray(existingDef.levels) && existingDef.levels.length && interiorByCode.size > 0);
  const linkOf = (l) => l.parentCode || l.sector || l.menuPath || 'Complaint';
  let levels, leafLevelCode, interior;
  if (preserve) {
    levels = existingDef.levels.slice().sort((a, b) => (Number(a.order) || 0) - (Number(b.order) || 0));
    const ll = levels.find((l) => l.isLeafServiceCode) || levels[levels.length - 1]; leafLevelCode = String((ll && ll.levelCode) || LEAF); interior = Array.from(interiorByCode.values());
  } else {
    levels = [{ levelCode: CATEGORY, order: 1, parentLevel: null, isFreeText: false, isLeafServiceCode: false, label: 'Category' }, { levelCode: LEAF, order: 2, parentLevel: CATEGORY, isFreeText: false, isLeafServiceCode: true, label: 'Sub-Type' }];
    leafLevelCode = LEAF; const cats = new Map();
    for (const d of defs) { const c = d.menuPath || 'Complaint'; if (!cats.has(c)) cats.set(c, d.menuPathName || c); }
    let i = 0; interior = Array.from(cats.entries()).map(([code, name]) => ({ levelCode: CATEGORY, code, parentCode: null, name, order: ++i, path: code }));
    interior.forEach((n) => interiorByCode.set(n.code, n));
  }
  console.log(PASS + ' mode=' + (preserve ? 'preserve' : 'derive') + ' · ' + interior.length + ' nodes · ' + defs.length + ' leaves');
  const unsafe = interior.map((n) => n.code).concat(defs.map((d) => d.serviceCode)).filter((c) => c && !SAFE.test(c));
  if (unsafe.length) { console.log(FAIL + ' Unsafe code(s): ' + Array.from(new Set(unsafe)).slice(0, 8).join(', ')); process.exit(1); }
  const interiorCodes = new Set(interior.map((n) => n.code));
  const collisions = defs.filter((d) => interiorCodes.has(d.serviceCode)).map((d) => d.serviceCode);
  if (collisions.length) { console.log(FAIL + ' Code collision(s): ' + Array.from(new Set(collisions)).slice(0, 5).join(', ')); process.exit(1); }
  if (DRY_RUN) { console.log(WARN + 'DRY-RUN: would write 1 def + ' + interior.length + ' nodes + ' + defs.length + ' leaves to ' + TARGETS.join(', ')); process.exit(0); }

  for (const t of TARGETS) await create(t, HDEF, HT, { hierarchyType: HT, active: true, levels });
  let ni = 0;
  for (const n of interior) { ni++; for (const t of TARGETS) await create(t, HIER, n.code, { hierarchyType: HT, levelCode: n.levelCode, code: n.code, parentCode: n.parentCode == null ? null : n.parentCode, name: n.name, order: n.order || ni, active: true, path: n.path || n.code }); }
  console.log(PASS + ' ' + interior.length + ' interior node(s) written');
  let li = 0;
  for (const d of defs) {
    const parentCode = linkOf(d); const pn = interiorByCode.get(parentCode); const parentPath = (pn && pn.path) || parentCode; li++;
    const data = { hierarchyType: HT, levelCode: leafLevelCode, code: d.serviceCode, parentCode, name: d.name, order: d.order || li, active: true, path: parentPath + '.' + d.serviceCode };
    if (d.department) data.department = d.department;
    if (d.departments && d.departments.length) data.departments = d.departments;
    if (d.slaHours != null) data.slaHours = d.slaHours;
    if (d.keywords) data.keywords = d.keywords;
    for (const t of TARGETS) await create(t, HIER, d.serviceCode, data);
  }
  console.log(PASS + ' ' + defs.length + ' leaf complaint type(s) written');
  try {
    const raw = [];
    for (const n of interiorByCode.values()) raw.push.apply(raw, nodeLoc(n.code, n.name));
    for (const d of defs) raw.push.apply(raw, nodeLoc(d.serviceCode, d.name));
    const seen = new Set(); const messages = raw.filter((m) => (seen.has(m.code) ? false : (seen.add(m.code), true)));
    if (!seen.has('CS_COMPLAINT_LOCATION')) messages.push({ code: 'CS_COMPLAINT_LOCATION', message: 'Complaint Location', module: 'rainmaker-pgr', locale: LOCALE });
    for (const t of TARGETS) await upsert(t, messages);
    console.log(PASS + ' localization seeded');
  } catch (e) { console.log(WARN + 'localization seed error (non-fatal): ' + (e && e.message ? e.message : e)); }
  try { await post('/localization/messages/cache-bust', { RequestInfo: RI }); } catch {}
  const vHier = await search(TARGETS[0], HIER, { limit: 5000 }); const scoped = (vHier.rows || []).filter((n) => n.hierarchyType === HT);
  console.log(PASS + ' verify: ' + scoped.filter((n) => n.department == null && n.slaHours == null).length + ' nodes · ' + scoped.filter((n) => n.department != null || n.slaHours != null).length + ' leaves present');
  console.log(PASS + ' Migration complete. NEXT: deploy the cutover backend + frontends, then retire ServiceDefs.');
})();
`;
}

function StepIcon({ status }: { status: MigrationStepStatus }) {
  switch (status) {
    case 'running':
      return <Loader2 className="w-4 h-4 text-primary animate-spin" />;
    case 'done':
      return <Check className="w-4 h-4 text-green-600" />;
    case 'error':
      return <X className="w-4 h-4 text-destructive" />;
    case 'skipped':
      return <MinusCircle className="w-4 h-4 text-muted-foreground" />;
    default:
      return <Circle className="w-3.5 h-3.5 text-muted-foreground/50" />;
  }
}

/**
 * "Migrate 2-level → hierarchy" action for the Complaint Hierarchies list.
 *
 * Visible only while the tenant has NO hierarchy definition yet (useListContext
 * total === 0). Clicking opens a popup that runs the additive migration
 * (docs/migration/complaint-type-2level-to-Nlevel.md) and shows each step's live
 * status. On success it refetches the list — a definition now exists, so the
 * button hides itself, matching "once done, hide the button".
 */
export function MigrateHierarchyAction() {
  const { total, refetch } = useListContext();
  const [open, setOpen] = useState(false);
  const [phase, setPhase] = useState<'idle' | 'running' | 'success' | 'failed'>('idle');
  const [steps, setSteps] = useState<StepState[]>(initialSteps);
  const [result, setResult] = useState<MigrationResult | null>(null);
  const [copied, setCopied] = useState(false);

  const tenants = useMemo(() => resolveMigrationTenants(), []);

  // The standalone .cjs an operator can run headless (node/psql tooling) outside
  // the configurator — same migration, parameterised with the resolved tenant.
  const standaloneScript = useMemo(
    () => buildStandaloneScript(tenants.managing, tenants.state),
    [tenants.managing, tenants.state]
  );

  // Hide once a hierarchy definition exists (or while the count is still loading).
  if (total !== 0) return null;

  const setStep = (key: string, status: MigrationStepStatus, detail?: string) =>
    setSteps((prev) =>
      prev.map((s) => (s.key === key ? { ...s, status, detail: detail ?? s.detail } : s))
    );

  const start = async () => {
    setPhase('running');
    setResult(null);
    setSteps(initialSteps());
    try {
      const res = await runComplaintHierarchyMigration({ onStep: setStep });
      setResult(res);
      setPhase(res.ok ? 'success' : 'failed');
    } catch (e) {
      setResult({
        ok: false,
        serviceDefs: 0,
        categories: 0,
        leaves: 0,
        tenants: tenants.targets,
        message: e instanceof Error ? e.message : 'Migration failed unexpectedly.',
      });
      setPhase('failed');
    }
  };

  const close = () => {
    setOpen(false);
    // If we just migrated, pull the fresh list so this button hides itself.
    if (phase === 'success') refetch();
    // Reset for a potential re-open (e.g. failure → retry path).
    setTimeout(() => {
      setPhase('idle');
      setSteps(initialSteps());
      setResult(null);
      setCopied(false);
    }, 200);
  };

  // Secondary action: copy the standalone migration script to the clipboard so
  // an operator can run it headless. navigator.clipboard is async + needs a
  // secure context; on failure we leave `copied` false (no false confirmation).
  const copyScript = async () => {
    try {
      await navigator.clipboard.writeText(standaloneScript);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  };

  // Offer the same script as a downloadable migrate.cjs (browser-side blob).
  const downloadScript = () => {
    const blob = new Blob([standaloneScript], { type: 'text/javascript' });
    const href = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = href;
    a.download = `migrate-${tenants.managing || 'tenant'}.cjs`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(href);
  };

  return (
    <>
      <Button variant="outline" size="sm" className="gap-1.5" onClick={() => setOpen(true)}>
        <GitMerge className="w-4 h-4" />
        Migrate from 2-level
      </Button>

      <Dialog open={open} onOpenChange={(o) => (o ? setOpen(true) : close())}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <GitMerge className="w-5 h-5 text-primary" />
              Migrate 2-level complaint types → hierarchy
            </DialogTitle>
            <DialogDescription className="text-xs sm:text-sm">
              Folds your complaint types into the single <span className="font-medium">ComplaintHierarchy</span>{' '}
              master — interior categories plus leaf sub-types (each leaf's code stays equal to its{' '}
              serviceCode). This is a <span className="font-medium">one-way</span> migration: afterwards you
              must deploy the updated backend &amp; frontends, then retire the old ServiceDefs master.
            </DialogDescription>
          </DialogHeader>

          {/* Target tenants */}
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <span>Target:</span>
            {tenants.targets.map((t) => (
              <code key={t} className="px-1.5 py-0.5 rounded bg-muted text-foreground font-mono">{t}</code>
            ))}
          </div>

          {/* Step checklist */}
          <ol className="space-y-2 my-1">
            {steps.map((s) => (
              <li key={s.key} className="flex items-start gap-3">
                <span className="mt-0.5 flex-shrink-0">
                  <StepIcon status={s.status} />
                </span>
                <div className="min-w-0">
                  <p
                    className={
                      'text-sm leading-tight ' +
                      (s.status === 'pending' || s.status === 'skipped'
                        ? 'text-muted-foreground'
                        : 'text-foreground')
                    }
                  >
                    {s.label}
                    {s.status === 'skipped' && <span className="ml-2 text-xs">(skipped)</span>}
                  </p>
                  {s.detail && <p className="text-xs text-muted-foreground font-mono truncate">{s.detail}</p>}
                </div>
              </li>
            ))}
          </ol>

          {/* Result banner */}
          {phase === 'success' && result && (
            <Alert variant="success">
              <Check className="w-4 h-4" />
              <AlertDescription className="text-sm">
                Migrated <span className="font-medium">{result.leaves}</span> complaint type
                {result.leaves === 1 ? '' : 's'} under <span className="font-medium">{result.categories}</span>{' '}
                categor{result.categories === 1 ? 'y' : 'ies'} into ComplaintHierarchy. Next: deploy the
                updated backend &amp; frontends for this tenant.
              </AlertDescription>
            </Alert>
          )}
          {phase === 'failed' && result?.message && (
            <Alert variant={result.serviceDefs === 0 ? 'warning' : 'destructive'}>
              <AlertTriangle className="w-4 h-4" />
              <AlertDescription className="text-sm">{result.message}</AlertDescription>
            </Alert>
          )}

          {/* Secondary action: take the migration to the command line. The script
              runs the exact same migration headless (node/psql tooling) for an
              operator who'd rather run it outside the configurator. */}
          <div className="flex items-center justify-between gap-2 border-t pt-3 mt-1">
            <span className="text-xs text-muted-foreground">Run outside the configurator?</span>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" className="gap-1.5" onClick={copyScript}>
                {copied ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy script'}
              </Button>
              <Button variant="outline" size="sm" className="gap-1.5" onClick={downloadScript}>
                <Download className="w-3.5 h-3.5" />
                Download .cjs
              </Button>
            </div>
          </div>

          <DialogFooter>
            {phase === 'idle' && (
              <>
                <Button variant="ghost" size="sm" onClick={close}>Cancel</Button>
                <Button size="sm" className="gap-1.5" onClick={start}>
                  Start migration <ArrowRight className="w-4 h-4" />
                </Button>
              </>
            )}
            {phase === 'running' && (
              <Button size="sm" disabled className="gap-1.5">
                <Loader2 className="w-4 h-4 animate-spin" /> Migrating…
              </Button>
            )}
            {phase === 'success' && (
              <Button size="sm" onClick={close}>Done</Button>
            )}
            {phase === 'failed' && (
              <>
                <Button variant="ghost" size="sm" onClick={close}>Close</Button>
                {result?.serviceDefs !== 0 && (
                  <Button size="sm" className="gap-1.5" onClick={start}>
                    <ArrowRight className="w-4 h-4" /> Retry
                  </Button>
                )}
              </>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
