import type { DataProvider } from 'react-admin';
import type { Catalog, CatalogTest, RunSummary } from './types';

/**
 * In-memory dataProvider over /tests/catalog.json.
 *
 * The catalog is a static file regenerated by the runner on every test run
 * and rsynced to the host. We fetch it once, cache it for the session, and
 * answer react-admin's getList/getOne/etc out of the cached object.
 *
 * Resources exposed:
 *   - tests : every CatalogTest, id = test.id (file:line:title)
 *   - runs  : every RunSummary, id = run.id (YYYY-MM-DD_HHMM_<short-sha>)
 *
 * Filtering, sorting, pagination, and full-text search are done client-side
 * — the catalog is small (~200 rows × ~5 KB each) and shipping a real API
 * for it would be overkill. If the catalog ever grows past that, swap this
 * for ra-data-json-server pointed at a thin Express layer.
 */

let cache: Promise<Catalog> | null = null;

function fetchCatalog(): Promise<Catalog> {
  if (cache) return cache;
  cache = (async () => {
    const url = `${import.meta.env.BASE_URL}catalog.json?t=${Date.now()}`;
    const resp = await fetch(url, { credentials: 'include' });
    if (!resp.ok) throw new Error(`catalog.json: HTTP ${resp.status}`);
    return resp.json() as Promise<Catalog>;
  })();
  return cache;
}

export function refreshCatalog(): Promise<Catalog> {
  cache = null;
  return fetchCatalog();
}

type Resource = 'tests' | 'runs';

function rowsFor(resource: Resource, c: Catalog): Array<CatalogTest | RunSummary> {
  if (resource === 'tests') return c.tests;
  if (resource === 'runs') return c.runs;
  throw new Error(`Unknown resource: ${resource}`);
}

function applyFilter<T extends Record<string, unknown>>(
  rows: T[],
  filter: Record<string, unknown>,
): T[] {
  if (!filter || Object.keys(filter).length === 0) return rows;
  return rows.filter(row => {
    for (const [k, v] of Object.entries(filter)) {
      if (k === 'q' && typeof v === 'string' && v) {
        const hay =
          (typeof row.title === 'string' ? row.title : '') +
          (typeof row.file === 'string' ? row.file : '') +
          (typeof row.describe === 'string' ? row.describe : '');
        if (!hay.toLowerCase().includes(v.toLowerCase())) return false;
        continue;
      }
      if (k === 'tag' && typeof v === 'string') {
        const tags = (row.tags as string[] | undefined) || [];
        if (!tags.includes(v)) return false;
        continue;
      }
      if (k === 'tags_any' && Array.isArray(v) && v.length) {
        const tags = (row.tags as string[] | undefined) || [];
        if (!v.some(want => tags.includes(want as string))) return false;
        continue;
      }
      // Per-facet OR-within-facet, AND-across-facets. UI passes
      // tags_any_persona / tags_any_area / etc.
      if (k.startsWith('tags_any_') && Array.isArray(v) && v.length) {
        const tags = (row.tags as string[] | undefined) || [];
        if (!v.some(want => tags.includes(want as string))) return false;
        continue;
      }
      // Direct equality on other fields.
      if (row[k] !== v) return false;
    }
    return true;
  });
}

function applySort<T extends Record<string, unknown>>(
  rows: T[],
  sort: { field: string; order: 'ASC' | 'DESC' } | undefined,
): T[] {
  if (!sort?.field) return rows;
  const dir = sort.order === 'DESC' ? -1 : 1;
  return [...rows].sort((a, b) => {
    const av = a[sort.field];
    const bv = b[sort.field];
    if (av === bv) return 0;
    if (av == null) return 1 * dir;
    if (bv == null) return -1 * dir;
    return av < bv ? -1 * dir : 1 * dir;
  });
}

export const dataProvider: DataProvider = {
  async getList(resource, params) {
    const c = await fetchCatalog();
    const all = rowsFor(resource as Resource, c);
    const filtered = applyFilter(
      all as unknown as Record<string, unknown>[],
      params.filter ?? {},
    );
    const sorted = applySort(filtered, params.sort);
    const page = params.pagination?.page ?? 1;
    const perPage = params.pagination?.perPage ?? 50;
    const start = (page - 1) * perPage;
    return {
      data: sorted.slice(start, start + perPage) as never[],
      total: sorted.length,
    };
  },

  async getOne(resource, params) {
    const c = await fetchCatalog();
    const all = rowsFor(resource as Resource, c) as Array<{ id: string }>;
    const found = all.find(r => r.id === params.id);
    if (!found) throw new Error(`${resource}#${params.id} not found`);
    return { data: found as never };
  },

  async getMany(resource, params) {
    const c = await fetchCatalog();
    const all = rowsFor(resource as Resource, c) as Array<{ id: string }>;
    const ids = new Set(params.ids.map(String));
    return { data: all.filter(r => ids.has(r.id)) as never[] };
  },

  async getManyReference(resource, params) {
    return this.getList(resource, {
      ...params,
      filter: { ...params.filter, [params.target]: params.id },
    });
  },

  // Catalog is read-only from the client's perspective — every mutation is
  // conceptually owned by the runner. Reject writes loudly so a stray
  // create-form doesn't pretend to succeed.
  async create() { throw new Error('catalog is read-only'); },
  async update() { throw new Error('catalog is read-only'); },
  async updateMany() { throw new Error('catalog is read-only'); },
  async delete() { throw new Error('catalog is read-only'); },
  async deleteMany() { throw new Error('catalog is read-only'); },
};
